namespace rosetta {

    namespace gen_detail {

        inline void write_file(const std::filesystem::path &path, std::string_view content) {
            std::filesystem::create_directories(path.parent_path());
            std::ofstream(path) << content;
        }

        // Substitute {{KEY}} placeholders. Plain string scan — no escapes.
        inline std::string
        render(std::string_view                                                     tmpl,
               std::initializer_list<std::pair<std::string_view, std::string_view>> vars) {
            std::string out{tmpl};
            for (const auto &[k, v] : vars) {
                std::string needle = "{{" + std::string(k) + "}}";
                for (std::string::size_type pos = 0;
                     (pos = out.find(needle, pos)) != std::string::npos; pos += v.size()) {
                    out.replace(pos, needle.size(), v);
                }
            }
            return out;
        }

        // -------- shared CMake fragment --------

        constexpr std::string_view CMAKE_HEADER =
            R"CMK(# Generated by rosetta::generate — do not edit by hand.
cmake_minimum_required(VERSION 3.28)

set(CLANG_P2996_ROOT "$ENV{HOME}/devs/c++/clang-p2996/build"
    CACHE PATH "Bloomberg clang-p2996 fork build directory")
if(NOT CMAKE_CXX_COMPILER)
    set(CMAKE_C_COMPILER   "${CLANG_P2996_ROOT}/bin/clang")
    set(CMAKE_CXX_COMPILER "${CLANG_P2996_ROOT}/bin/clang++")
endif()
)CMK";

        // -------- python --------

        constexpr std::string_view PY_CPP =
            R"CPP(// Generated by rosetta::generate — do not edit by hand.
#include "{{HEADER}}"
#include <rosetta/visitors/pybind_visitor.h>

PYBIND11_MODULE({{LIB}}, m) {
    m.doc() = "Auto-generated bindings for {{CLASS}}.";
    rosetta::bind_pybind<{{CLASS}}>(m, "{{CLASS}}");
}
)CPP";

        constexpr std::string_view PY_CMAKE = R"CMK({{HEADER_BLOCK}}
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

execute_process(
    COMMAND python3 -c "import sys; print(sys.executable)"
    OUTPUT_VARIABLE Python_EXECUTABLE
    OUTPUT_STRIP_TRAILING_WHITESPACE)
set(Python3_EXECUTABLE "${Python_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(PYBIND11_FINDPYTHON ON)

if(NOT pybind11_DIR)
    execute_process(
        COMMAND ${Python_EXECUTABLE} -m pybind11 --cmakedir
        OUTPUT_VARIABLE pybind11_DIR
        OUTPUT_STRIP_TRAILING_WHITESPACE)
endif()
find_package(pybind11 REQUIRED CONFIG)

pybind11_add_module({{LIB}} NO_EXTRAS auto_pybind.cpp)

target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

target_compile_options({{LIB}} PRIVATE
    -freflection -freflection-latest -fexperimental-library -fannotation-attributes)

target_link_options({{LIB}} PRIVATE
    -nostdlib++ -L${CLANG_P2996_ROOT}/lib -Wl,-rpath,${CLANG_P2996_ROOT}/lib
    -lc++ -lc++abi)

add_custom_command(TARGET {{LIB}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        $<TARGET_FILE:{{LIB}}>
        ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
)CMK";

        // -------- node (N-API) --------

        constexpr std::string_view NODE_CPP =
            R"CPP(// Generated by rosetta::generate — do not edit by hand.
#include "{{HEADER}}"
#include <rosetta/visitors/napi_visitor.h>

Napi::Object Init(Napi::Env env, Napi::Object exports) {
    exports.Set("{{CLASS}}", rosetta::bind_napi<{{CLASS}}>(env, "{{CLASS}}"));
    return exports;
}

NODE_API_MODULE({{LIB}}, Init)
)CPP";

        constexpr std::string_view NODE_CMAKE = R"CMK({{HEADER_BLOCK}}
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

if(NOT NODE_ADDON_API_DIR)
    execute_process(
        COMMAND node -p "require('node-addon-api').include"
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE NODE_ADDON_API_DIR
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    string(REGEX REPLACE "^\"|\"$" "" NODE_ADDON_API_DIR "${NODE_ADDON_API_DIR}")
endif()

add_library({{LIB}} SHARED auto_napi.cpp ${CMAKE_JS_SRC})
set_target_properties({{LIB}} PROPERTIES PREFIX "" SUFFIX ".node")

target_include_directories({{LIB}} PRIVATE
    ${CMAKE_JS_INC}
    ${NODE_ADDON_API_DIR}
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

target_link_libraries({{LIB}} PRIVATE ${CMAKE_JS_LIB})

target_compile_definitions({{LIB}} PRIVATE NAPI_VERSION=8)

target_compile_options({{LIB}} PRIVATE
    -freflection -freflection-latest -fexperimental-library -fannotation-attributes)

target_link_options({{LIB}} PRIVATE
    -nostdlib++ -L${CLANG_P2996_ROOT}/lib -Wl,-rpath,${CLANG_P2996_ROOT}/lib
    -lc++ -lc++abi)

if(APPLE)
    target_link_options({{LIB}} PRIVATE -Wl,-undefined,dynamic_lookup)
endif()

add_custom_command(TARGET {{LIB}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        $<TARGET_FILE:{{LIB}}>
        ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
)CMK";

        constexpr std::string_view NODE_PACKAGE = R"JSON({
  "name": "{{LIB}}",
  "version": "1.0.0",
  "private": true,
  "description": "Auto-generated N-API bindings for {{CLASS}}.",
  "main": "index.js",
  "scripts": {
    "build": "cmake-js compile",
    "rebuild": "cmake-js rebuild"
  },
  "devDependencies": {
    "cmake-js": "^7.3.0",
    "node-addon-api": "^8.0.0"
  }
}
)JSON";

        // -------- rest --------

        constexpr std::string_view REST_CPP =
            R"CPP(// Generated by rosetta::generate — do not edit by hand.
#include "{{HEADER}}"
#include <rosetta/visitors/rest_visitor.h>
#include <cstdio>
#include <cstdlib>

int main(int argc, char **argv) {
    const char *host = "127.0.0.1";
    int         port = 8080;
    if (argc > 1) host = argv[1];
    if (argc > 2) port = std::atoi(argv[2]);

    httplib::Server          server;
    rosetta::Store<{{CLASS}}> store;
    rosetta::bind_rest<{{CLASS}}>(server, "/{{CLASS}}", store);

    std::fprintf(stderr, "serving on http://%s:%d\n", host, port);
    server.listen(host, port);
    return 0;
}
)CPP";

        constexpr std::string_view REST_CMAKE = R"CMK({{HEADER_BLOCK}}
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

include(FetchContent)
FetchContent_Declare(httplib
    GIT_REPOSITORY https://github.com/yhirose/cpp-httplib.git
    GIT_TAG        v0.18.1)
FetchContent_Declare(json
    GIT_REPOSITORY https://github.com/nlohmann/json.git
    GIT_TAG        v3.11.3)
FetchContent_MakeAvailable(httplib json)

add_executable({{LIB}} auto_rest.cpp)

target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

target_link_libraries({{LIB}} PRIVATE httplib::httplib nlohmann_json::nlohmann_json)

target_compile_options({{LIB}} PRIVATE
    -freflection -freflection-latest -fexperimental-library -fannotation-attributes)

target_link_options({{LIB}} PRIVATE
    -nostdlib++ -L${CLANG_P2996_ROOT}/lib -Wl,-rpath,${CLANG_P2996_ROOT}/lib
    -lc++ -lc++abi)
)CMK";

        // -------- web (emscripten) --------

        constexpr std::string_view WEB_CPP =
            R"CPP(// Generated by rosetta::generate — do not edit by hand.
#include "{{HEADER}}"
#include <rosetta/visitors/emscripten_visitor.hpp>

EMSCRIPTEN_BINDINGS({{LIB}}) {
    rosetta::bind_emscripten<{{CLASS}}>("{{CLASS}}");
}
)CPP";

        constexpr std::string_view WEB_CMAKE =
            R"CMK(# Generated by rosetta::generate — do not edit by hand.
cmake_minimum_required(VERSION 3.28)
project({{LIB}}_binding CXX)

if(NOT EMSCRIPTEN)
    message(FATAL_ERROR "Configure via `emcmake cmake ...` (emsdk required).")
endif()

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

add_executable({{LIB}} auto_emscripten.cpp)

target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

target_compile_options({{LIB}} PRIVATE
    -freflection -freflection-latest -fexperimental-library -fannotation-attributes)

target_link_options({{LIB}} PRIVATE
    --bind -sMODULARIZE=1 -sEXPORT_NAME=createModule
    -sENVIRONMENT=node,web -sALLOW_MEMORY_GROWTH=1 -sDISABLE_EXCEPTION_CATCHING=0)

set_target_properties({{LIB}} PROPERTIES SUFFIX ".js")
)CMK";

        // -------- emitter dispatch --------

        struct Ctx {
            std::string class_name;
            std::string lib_name;
            std::string header;
            std::string user_include;
            std::string rosetta_include;
            std::string readme_body;
        };

#define ROSETTA_GEN_VARS(c)                                                       \
    {                                                                             \
        {"CLASS", (c).class_name}, {"LIB", (c).lib_name}, {"HEADER", (c).header}, \
            {"HEADER_BLOCK", CMAKE_HEADER}, {"USER_INCLUDE", (c).user_include}, { \
            "ROSETTA_INCLUDE", (c).rosetta_include                                \
        }                                                                         \
    }

        inline std::string readme(std::string_view backend, const Ctx &c) {
            std::string s = "# `" + c.lib_name + "` (";
            s += backend;
            s += ")\n\nAuto-generated bindings for `";
            s += c.class_name;
            s += "`.\n\n";
            s += c.readme_body;
            return s;
        }

        inline void emit_python(const std::filesystem::path &root, const Ctx &c) {
            auto dir = root / "python";
            write_file(dir / "auto_pybind.cpp", render(PY_CPP, ROSETTA_GEN_VARS(c)));
            write_file(dir / "CMakeLists.txt", render(PY_CMAKE, ROSETTA_GEN_VARS(c)));
            write_file(dir / "README.md", readme("python", c));
        }

        inline void emit_node(const std::filesystem::path &root, const Ctx &c) {
            auto dir = root / "node";
            write_file(dir / "auto_napi.cpp", render(NODE_CPP, ROSETTA_GEN_VARS(c)));
            write_file(dir / "CMakeLists.txt", render(NODE_CMAKE, ROSETTA_GEN_VARS(c)));
            write_file(dir / "package.json", render(NODE_PACKAGE, ROSETTA_GEN_VARS(c)));
            write_file(dir / "README.md", readme("node", c));
        }

        inline void emit_rest(const std::filesystem::path &root, const Ctx &c) {
            auto dir = root / "rest";
            write_file(dir / "auto_rest.cpp", render(REST_CPP, ROSETTA_GEN_VARS(c)));
            write_file(dir / "CMakeLists.txt", render(REST_CMAKE, ROSETTA_GEN_VARS(c)));
            write_file(dir / "README.md", readme("rest", c));
        }

        inline void emit_web(const std::filesystem::path &root, const Ctx &c) {
            auto dir = root / "web";
            write_file(dir / "auto_emscripten.cpp", render(WEB_CPP, ROSETTA_GEN_VARS(c)));
            write_file(dir / "CMakeLists.txt", render(WEB_CMAKE, ROSETTA_GEN_VARS(c)));
            write_file(dir / "README.md", readme("web", c));
        }

    } // namespace gen_detail

    /**
     * @brief Scaffold a per-backend binding project for T under opt.out_dir,
     * driven by the `rosetta::binding_info<T>` trait specialization.
     */
    template <typename T> inline void generate(const GenerateOptions &opt) {
        using info                       = binding_info<T>;
        constexpr const char *class_name = std::define_static_string(std::meta::identifier_of(^^T));

        gen_detail::Ctx c;
        c.class_name      = class_name;
        c.lib_name        = info::lib;
        c.header          = info::header;
        c.user_include    = opt.user_include.string();
        c.rosetta_include = opt.rosetta_include.string();
        c.readme_body     = generate_markdown<T>();

        for (std::string_view t : info::targets) {
            if (t == "python")
                gen_detail::emit_python(opt.out_dir, c);
            else if (t == "node")
                gen_detail::emit_node(opt.out_dir, c);
            else if (t == "rest")
                gen_detail::emit_rest(opt.out_dir, c);
            else if (t == "web")
                gen_detail::emit_web(opt.out_dir, c);
        }
    }

} // namespace rosetta
