namespace rosetta {

    namespace gen_detail {

        inline void write_file(const std::filesystem::path &path, std::string_view content) {
            std::filesystem::create_directories(path.parent_path());
            std::ofstream(path) << content;
        }

        // Substitute {{KEY}} placeholders. Plain string scan — no escapes.
        inline std::string
        render(std::string_view                                                     tmpl,
               std::initializer_list<std::pair<std::string_view, std::string_view>> vars) {
            std::string out{tmpl};
            for (const auto &[k, v] : vars) {
                std::string needle = "{{" + std::string(k) + "}}";
                for (std::string::size_type pos = 0;
                     (pos = out.find(needle, pos)) != std::string::npos; pos += v.size()) {
                    out.replace(pos, needle.size(), v);
                }
            }
            return out;
        }

        // Reflected identifier of T as a runtime string.
        template <typename T> inline std::string class_name() {
            constexpr const char *n = std::define_static_string(std::meta::identifier_of(^^T));
            return std::string(n);
        }

        // -------- shared CMake fragment --------

        constexpr std::string_view CMAKE_HEADER =
            R"CMK(# Generated by rosetta::generate — do not edit by hand.
cmake_minimum_required(VERSION 3.28)

set(CLANG_P2996_ROOT "$ENV{HOME}/devs/c++/clang-p2996/build"
    CACHE PATH "Bloomberg clang-p2996 fork build directory")
if(NOT CMAKE_CXX_COMPILER)
    set(CMAKE_C_COMPILER   "${CLANG_P2996_ROOT}/bin/clang")
    set(CMAKE_CXX_COMPILER "${CLANG_P2996_ROOT}/bin/clang++")
endif()
)CMK";

        // -------- shared render helpers (used by every backend) --------

        // One `#include "..."` line per class / enum — shared by every backend.
        // Headers are de-duplicated (a class and enum may share a header).
        // rosetta's annotations are included first so user headers that carry
        // `[[ = rosetta::doc{...} ]]` annotations parse (they don't include
        // rosetta themselves).
        inline std::string includes_of(const GenContext &c) {
            std::string s = "#include <rosetta/annotations.h>\n";
            auto        add = [&](const std::string &h) {
                const std::string line = "#include \"" + h + "\"\n";
                if (s.find(line) == std::string::npos) {
                    s += line;
                }
            };
            for (const auto &k : c.classes) {
                add(k.header);
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            // Out-of-line annotations: backends whose emitted .cpp re-walks the
            // type at its own compile time (python / node) need the
            // ann_json_source<T> specialization in their TU, or they would see
            // the empty primary and lose the side-car. Re-emit it here, after
            // the class headers (so T is complete). Backends that render purely
            // from GenClass ignore the unused specialization.
            std::string anns;
            for (const auto &k : c.classes) {
                if (k.annotations_json.empty()) {
                    continue;
                }
                std::string bytes;
                char        buf[16];
                for (unsigned char ch : k.annotations_json) {
                    std::snprintf(buf, sizeof buf, "char(0x%02x), ", ch);
                    bytes += buf;
                }
                anns += "template <> inline constexpr auto rosetta::detail::ann_storage<" + k.name +
                        "> =\n    std::to_array<char>({" + bytes + "'\\0'});\n" +
                        "template <> inline constexpr std::string_view rosetta::ann_json_source<" +
                        k.name + "> =\n    std::string_view{rosetta::detail::ann_storage<" + k.name +
                        ">.data(), rosetta::detail::ann_storage<" + k.name + ">.size() - 1};\n";
            }
            if (!anns.empty()) {
                s += "#include <rosetta/annotate.h>\n" + anns;
            }
            return s;
        }

        // The per-class reference docs, concatenated into the README body.
        inline std::string readme_body_of(const std::vector<GenClass> &classes) {
            std::string s;
            for (const auto &c : classes) {
                s += c.doc + "\n";
            }
            return s;
        }

        // CMake / package vars — backend source uses {{INCLUDES}}/{{BINDINGS}}
        // which are passed separately by render_source().
        inline std::string render_meta(std::string_view tmpl, const GenContext &c) {
            return render(tmpl, {{"LIB", c.lib},
                                 {"HEADER_BLOCK", CMAKE_HEADER},
                                 {"USER_INCLUDE", c.user_include},
                                 {"ROSETTA_INCLUDE", c.rosetta_include}});
        }

        inline std::string render_source(std::string_view tmpl, const GenContext &c,
                                         std::string_view binds) {
            return render(tmpl, {{"LIB", c.lib},
                                 {"INCLUDES", includes_of(c)},
                                 {"BINDINGS", binds}});
        }

        // Can a value of this type cross a JSON boundary (REST / OpenAPI)?
        // Scalars, bools, strings, enums (as their underlying int), and vectors
        // of those qualify; user object types and std::function do not. Shared
        // by the REST and OpenAPI backends so they describe the same surface.
        inline bool jsonable_type(const GenType &t) {
            if (t.kind == "number" || t.kind == "boolean" || t.kind == "string" ||
                t.kind == "enum") {
                return true;
            }
            if (t.kind == "vector") {
                return !t.element.empty() && jsonable_type(t.element.front());
            }
            return false; // object / void / unknown
        }

        // A method is exposable over JSON only if its return and every parameter
        // type can cross the boundary.
        inline bool jsonable_method(const GenMethod &m) {
            if (!(m.ret.kind == "void" || jsonable_type(m.ret))) {
                return false;
            }
            for (const auto &p : m.params) {
                if (!jsonable_type(p.type)) {
                    return false;
                }
            }
            return true;
        }

        // A free function is exposable over JSON under the same rule.
        inline bool jsonable_function(const GenFunction &f) {
            if (!(f.ret.kind == "void" || jsonable_type(f.ret))) {
                return false;
            }
            for (const auto &p : f.params) {
                if (!jsonable_type(p.type)) {
                    return false;
                }
            }
            return true;
        }

        inline std::string readme(std::string_view backend, const GenContext &c) {
            std::string s = "# `" + c.lib + "` (";
            s += backend;
            s += ")\n\nAuto-generated bindings.\n\n";
            s += readme_body_of(c.classes);
            for (const auto &e : c.enums) {
                s += e.doc + "\n";
            }
            if (!c.functions.empty()) {
                s += "# Functions\n\n";
                for (const auto &f : c.functions) {
                    s += "- `" + f.name + "`";
                    if (!f.doc.empty()) {
                        s += " — " + f.doc;
                    }
                    s += "\n";
                }
                s += "\n";
            }
            return s;
        }

        // -------- reflection IR (for pure-data backends) --------

        template <typename T> struct is_vec : std::false_type {};
        template <typename U, typename A> struct is_vec<std::vector<U, A>> : std::true_type {};

        template <typename T> struct is_func : std::false_type {};
        template <typename R, typename... A> struct is_func<std::function<R(A...)>> : std::true_type {};

        // Map a C++ type to the language-neutral GenType descriptor.
        template <typename T> inline GenType type_descriptor() {
            using U = std::remove_cvref_t<T>;
            GenType g;
            if constexpr (std::is_void_v<U>) {
                g.kind = "void";
            } else if constexpr (std::is_same_v<U, bool>) {
                g.kind = "boolean";
            } else if constexpr (std::is_same_v<U, std::string>) {
                g.kind = "string";
            } else if constexpr (std::is_arithmetic_v<U>) {
                g.kind    = "number";
                g.integer = std::is_integral_v<U>;
            } else if constexpr (is_func<U>::value) {
                g.kind = "unknown";
            } else if constexpr (is_vec<U>::value) {
                g.kind = "vector";
                g.element.push_back(type_descriptor<typename U::value_type>());
            } else if constexpr (std::is_enum_v<U>) {
                g.kind   = "enum";
                g.object = class_name<U>();
            } else if constexpr (std::is_class_v<U>) {
                g.kind   = "object";
                g.object = class_name<U>();
            } else {
                g.kind = "unknown";
            }
            return g;
        }

        template <std::meta::info Fn, std::size_t... Is>
        inline std::vector<GenParam> params_impl(std::index_sequence<Is...>) {
            constexpr auto        ps = std::define_static_array(std::meta::parameters_of(Fn));
            std::vector<GenParam> out;
            (out.push_back(GenParam{
                 "arg" + std::to_string(Is),
                 type_descriptor<std::remove_cvref_t<typename[:std::meta::type_of(ps[Is]):]>>()}),
             ...);
            return out;
        }

        template <std::meta::info Fn> inline std::vector<GenParam> params_of() {
            constexpr auto n = std::define_static_array(std::meta::parameters_of(Fn)).size();
            return params_impl<Fn>(std::make_index_sequence<n>{});
        }

        // Walk visitor that collects member type info into a GenClass.
        struct IRVisitor {
            GenClass &out;

            template <std::meta::info Fld, auto... Anns> void field(const char *name) {
                GenField gf;
                gf.name = name;
                gf.type = type_descriptor<std::remove_cvref_t<typename[:std::meta::type_of(Fld):]>>();
                gf.is_readonly = ann::has<readonly>(Anns...);
                gf.doc         = ann::get_or<doc>(doc{""}, Anns...).text;
                if constexpr (ann::has<range>(Anns...)) {
                    constexpr auto r = ann::get_or<range>(range{0, 0}, Anns...);
                    gf.range         = GenRange{true, r.min, r.max};
                }
                if constexpr (ann::has<combobox>(Anns...)) {
                    constexpr auto cb = ann::get_or<combobox>(combobox{}, Anns...);
                    for (std::size_t i = 0; i < cb.count; ++i) {
                        gf.choices.push_back(cb.choices[i]);
                    }
                }
                out.fields.push_back(std::move(gf));
            }

            template <std::meta::info Fn, auto... Anns> void method_instance(const char *name) {
                push_method<Fn>(name, false, ann::get_or<doc>(doc{""}, Anns...).text);
            }

            template <std::meta::info Fn, auto... Anns> void method_static(const char *name) {
                push_method<Fn>(name, true, ann::get_or<doc>(doc{""}, Anns...).text);
            }

            template <std::meta::info Ctor, auto... /*Anns*/> void constructor() {
                out.ctors.push_back(params_of<Ctor>());
            }

          private:
            template <std::meta::info Fn>
            void push_method(const char *name, bool is_static, const char *docstr) {
                out.methods.push_back(GenMethod{
                    name, is_static,
                    type_descriptor<std::remove_cvref_t<typename[:std::meta::return_type_of(Fn):]>>(),
                    params_of<Fn>(), std::string(docstr)});
            }
        };

        // Erase one class to plain data — the only place reflection runs.
        template <typename T> inline GenClass describe() {
            GenClass gc;
            gc.name   = class_name<T>();
            gc.header = binding_info<T>::header;
            gc.doc    = generate_markdown<T>();
            // Carry the out-of-line annotation source so re-walking backends
            // (python / node) can re-emit it into their own TUs — see
            // includes_of(). Empty when the class has no side-car.
            gc.annotations_json = std::string(rosetta::ann_json_source<T>);
            IRVisitor v{gc};
            walk<T>(v);
            return gc;
        }

        // Render an enum's markdown fragment (heading + value table). Used both
        // as the GenEnum::doc (README body) and by the markdown backend.
        inline std::string render_enum_markdown(const GenEnum &ge) {
            std::string s = "# " + ge.name + "\n\n";
            s += "_enum";
            if (!ge.underlying.empty()) {
                s += " : " + ge.underlying;
            }
            s += "_\n\n";
            s += "| Name | Value |\n|------|-------|\n";
            for (const auto &v : ge.values) {
                s += "| `" + v.name + "` | " + std::to_string(v.value) + " |\n";
            }
            return s;
        }

        // Erase one enum to plain data — collects its enumerators via
        // reflection. The companion to describe() for enum pack elements.
        template <typename T> inline GenEnum describe_enum() {
            GenEnum ge;
            ge.name       = class_name<T>();
            ge.header     = binding_info<T>::header;
            ge.underlying = std::define_static_string(
                std::meta::display_string_of(std::meta::underlying_type(^^T)));
            template for (constexpr auto e :
                          std::define_static_array(std::meta::enumerators_of(^^T))) {
                constexpr const char *en = std::define_static_string(std::meta::identifier_of(e));
                ge.values.push_back(GenEnumerator{en, static_cast<long long>([:e:])});
            }
            ge.doc = render_enum_markdown(ge);
            return ge;
        }

    } // namespace gen_detail

} // namespace rosetta

// -------- built-in backends (one file each) --------
// Each defines its templates + a gen_detail::*Backend, using the shared
// render helpers above. New backends register the same way (see
// docs/EXTENDING_BACKEND.md) without touching generate().
#include "json_backend.hxx"
#include "julia_backend.hxx"
#include "markdown_backend.hxx"
#include "node_backend.hxx"
#include "openapi_backend.hxx"
#include "python_backend.hxx"
#include "rest_backend.hxx"
#include "typescript_backend.hxx"
#include "wasm_backend.hxx"

namespace rosetta {

    // -------- backend registry --------

    inline std::map<std::string, std::shared_ptr<Backend>> &backend_registry() {
        static std::map<std::string, std::shared_ptr<Backend>> reg = [] {
            std::map<std::string, std::shared_ptr<Backend>> m;
            m["python"]     = std::make_shared<gen_detail::PythonBackend>();
            m["node"]       = std::make_shared<gen_detail::NodeBackend>();
            m["julia"]      = std::make_shared<gen_detail::JuliaBackend>();
            m["rest"]       = std::make_shared<gen_detail::RestBackend>();
            m["wasm"]       = std::make_shared<gen_detail::WasmBackend>();
            m["typescript"] = std::make_shared<gen_detail::TypeScriptBackend>();
            m["markdown"]   = std::make_shared<gen_detail::MarkdownBackend>();
            m["json"]       = std::make_shared<gen_detail::JsonBackend>();
            m["openapi"]    = std::make_shared<gen_detail::OpenApiBackend>();
            return m;
        }();
        return reg;
    }

    inline void register_backend(std::string lang, std::shared_ptr<Backend> backend) {
        backend_registry()[std::move(lang)] = std::move(backend);
    }

    // Erase one free function (named by its reflection F) to plain data. Called
    // from the generated driver, which splices `^^name` for each manifest-listed
    // function. `qualified` is the C++ spelling backends emit for `&fn`; `doc`
    // comes from the manifest (free functions carry no in-source annotation, so
    // user headers stay untouched).
    template <std::meta::info F>
    inline GenFunction make_function(const char *qualified, const char *header,
                                     const char *doc) {
        GenFunction gf;
        gf.name      = std::define_static_string(std::meta::identifier_of(F));
        gf.qualified = qualified;
        gf.header    = header;
        gf.ret       = gen_detail::type_descriptor<
            std::remove_cvref_t<typename[:std::meta::return_type_of(F):]>>();
        gf.params = gen_detail::params_of<F>();
        gf.doc    = doc;
        return gf;
    }

    template <typename... Ts> inline void generate(const GenerateOptions &opt) {
        // Erase the type pack into plain data once; backends do no reflection.
        // Enum pack elements go to `enums`, everything else to `classes`.
        std::vector<GenClass> classes;
        std::vector<GenEnum>  enums;
        (
            [&] {
                if constexpr (std::is_enum_v<Ts>)
                    enums.push_back(gen_detail::describe_enum<Ts>());
                else {
                    classes.push_back(gen_detail::describe<Ts>());
                }
            }(),
            ...);

        for (const TargetSpec &t : opt.targets) {
            auto &reg = backend_registry();
            auto  it  = reg.find(t.lang);
            if (it == reg.end() || !it->second) {
                std::fprintf(
                    stderr,
                    "rosetta::generate: no backend registered for target '%s' — skipped\n",
                    t.lang.c_str());
                continue;
            }
            it->second->emit(GenContext{opt.out_dir, t.name, classes, enums,
                                        opt.functions, opt.user_include.string(),
                                        opt.rosetta_include.string()});
        }
    }

} // namespace rosetta
