namespace rosetta {

    namespace gen_detail {

        inline void write_file(const std::filesystem::path &path, std::string_view content) {
            std::filesystem::create_directories(path.parent_path());
            std::ofstream(path) << content;
        }

        // Substitute {{KEY}} placeholders. Plain string scan — no escapes.
        // (Named `subst`, not `render`, so it isn't shadowed by Backend::render
        // when called unqualified inside a backend's emit().)
        inline std::string
        subst(std::string_view                                                     tmpl,
              std::initializer_list<std::pair<std::string_view, std::string_view>> vars) {
            std::string out{tmpl};
            for (const auto &[k, v] : vars) {
                std::string needle = "{{" + std::string(k) + "}}";
                for (std::string::size_type pos = 0;
                     (pos = out.find(needle, pos)) != std::string::npos; pos += v.size()) {
                    out.replace(pos, needle.size(), v);
                }
            }
            return out;
        }

        // Look up a type-erased annotation by type in a GenClass/GenField's
        // `annotations`. Returns nullptr if absent. Lets a backend read its own
        // annotation kinds without the core ever naming them.
        template <class A> inline const A *find_annotation(const std::vector<std::any> &anns) {
            for (const auto &a : anns) {
                if (const A *p = std::any_cast<A>(&a)) {
                    return p;
                }
            }
            return nullptr;
        }

        // Reflected identifier of T as a runtime string.
        template <typename T> inline std::string class_name() {
            constexpr const char *n = std::define_static_string(std::meta::identifier_of(^^T));
            return std::string(n);
        }

        // -------- shared CMake fragment --------

        constexpr std::string_view CMAKE_HEADER =
            R"CMK(# Generated by rosetta::generate — do not edit by hand.
cmake_minimum_required(VERSION 3.28)

set(CLANG_P2996_ROOT "$ENV{HOME}/devs/c++/clang-p2996/build"
    CACHE PATH "Bloomberg clang-p2996 fork build directory")
if(NOT CMAKE_CXX_COMPILER)
    set(CMAKE_C_COMPILER   "${CLANG_P2996_ROOT}/bin/clang")
    set(CMAKE_CXX_COMPILER "${CLANG_P2996_ROOT}/bin/clang++")
endif()
)CMK";

        // -------- shared render helpers (used by every backend) --------

        // One `#include "..."` line per class / enum — shared by every backend.
        // Headers are de-duplicated (a class and enum may share a header).
        // rosetta's annotations are included first so user headers that carry
        // `[[ = rosetta::doc{...} ]]` annotations parse (they don't include
        // rosetta themselves).
        inline std::string includes_of(const GenContext &c) {
            std::string s = "#include <rosetta/annotations.h>\n";
            auto        add = [&](const std::string &h) {
                const std::string line = "#include \"" + h + "\"\n";
                if (s.find(line) == std::string::npos) {
                    s += line;
                }
            };
            for (const auto &k : c.classes) {
                add(k.header);
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            // Out-of-line annotations: backends whose emitted .cpp re-walks the
            // type at its own compile time (python / node) need the
            // ann_json_source<T> specialization in their TU, or they would see
            // the empty primary and lose the side-car. Re-emit it here, after
            // the class headers (so T is complete). Backends that render purely
            // from GenClass ignore the unused specialization.
            std::string anns;
            for (const auto &k : c.classes) {
                if (k.annotations_json.empty()) {
                    continue;
                }
                std::string bytes;
                char        buf[16];
                for (unsigned char ch : k.annotations_json) {
                    std::snprintf(buf, sizeof buf, "char(0x%02x), ", ch);
                    bytes += buf;
                }
                anns += "template <> inline constexpr auto rosetta::detail::ann_storage<" + k.name +
                        "> =\n    std::to_array<char>({" + bytes + "'\\0'});\n" +
                        "template <> inline constexpr std::string_view rosetta::ann_json_source<" +
                        k.name + "> =\n    std::string_view{rosetta::detail::ann_storage<" + k.name +
                        ">.data(), rosetta::detail::ann_storage<" + k.name + ">.size() - 1};\n";
            }
            if (!anns.empty()) {
                s += "#include <rosetta/annotate.h>\n" + anns;
            }
            return s;
        }

        // The per-class reference docs, concatenated into the README body.
        inline std::string readme_body_of(const std::vector<GenClass> &classes) {
            std::string s;
            for (const auto &c : classes) {
                s += c.doc + "\n";
            }
            return s;
        }

        // CMake / package vars — backend source uses {{INCLUDES}}/{{BINDINGS}}
        // which are passed separately by render_source().
        inline std::string render_meta(std::string_view tmpl, const GenContext &c) {
            return subst(tmpl, {{"LIB", c.lib},
                                {"HEADER_BLOCK", CMAKE_HEADER},
                                {"USER_INCLUDE", c.user_include},
                                {"ROSETTA_INCLUDE", c.rosetta_include}});
        }

        inline std::string render_source(std::string_view tmpl, const GenContext &c,
                                         std::string_view binds) {
            return subst(tmpl, {{"LIB", c.lib},
                                {"INCLUDES", includes_of(c)},
                                {"BINDINGS", binds}});
        }

        // Can a value of this type cross a JSON boundary (REST / OpenAPI)?
        // Scalars, bools, strings, enums (as their underlying int), and vectors
        // of those qualify; user object types and std::function do not. Shared
        // by the REST and OpenAPI backends so they describe the same surface.
        inline bool jsonable_type(const GenType &t) {
            if (t.kind == "number" || t.kind == "boolean" || t.kind == "string" ||
                t.kind == "enum") {
                return true;
            }
            if (t.kind == "vector") {
                return !t.element.empty() && jsonable_type(t.element.front());
            }
            return false; // object / void / unknown
        }

        // A method is exposable over JSON only if its return and every parameter
        // type can cross the boundary.
        inline bool jsonable_method(const GenMethod &m) {
            if (!(m.ret.kind == "void" || jsonable_type(m.ret))) {
                return false;
            }
            for (const auto &p : m.params) {
                if (!jsonable_type(p.type)) {
                    return false;
                }
            }
            return true;
        }

        // A free function is exposable over JSON under the same rule.
        inline bool jsonable_function(const GenFunction &f) {
            if (!(f.ret.kind == "void" || jsonable_type(f.ret))) {
                return false;
            }
            for (const auto &p : f.params) {
                if (!jsonable_type(p.type)) {
                    return false;
                }
            }
            return true;
        }

        inline std::string readme(std::string_view backend, const GenContext &c) {
            std::string s = "# `" + c.lib + "` (";
            s += backend;
            s += ")\n\nAuto-generated bindings.\n\n";
            s += readme_body_of(c.classes);
            for (const auto &e : c.enums) {
                s += e.doc + "\n";
            }
            if (!c.functions.empty()) {
                s += "# Functions\n\n";
                for (const auto &f : c.functions) {
                    s += "- `" + f.name + "`";
                    if (!f.doc.empty()) {
                        s += " — " + f.doc;
                    }
                    s += "\n";
                }
                s += "\n";
            }
            return s;
        }

        // -------- reflection IR (for pure-data backends) --------

        template <typename T> struct is_vec : std::false_type {};
        template <typename U, typename A> struct is_vec<std::vector<U, A>> : std::true_type {};

        template <typename T> struct is_func : std::false_type {};
        template <typename R, typename... A> struct is_func<std::function<R(A...)>> : std::true_type {};

        // Prettify a canonical type spelling for human docs: display_string_of
        // yields e.g. basic_string<char, …>; show std::string instead.
        inline std::string prettify(std::string s) {
            struct Rule {
                const char *from;
                const char *to;
            };
            static constexpr Rule rules[] = {
                {"basic_string<char, char_traits<char>, allocator<char>>", "std::string"},
                {"basic_string_view<char, char_traits<char>>", "std::string_view"},
            };
            for (const auto &r : rules) {
                std::string::size_type pos  = 0;
                const std::string      from = r.from;
                const std::string      to   = r.to;
                while ((pos = s.find(from, pos)) != std::string::npos) {
                    s.replace(pos, from.size(), to);
                    pos += to.size();
                }
            }
            return s;
        }

        // Map a C++ type to the language-neutral GenType descriptor.
        template <typename T> inline GenType type_descriptor() {
            using U = std::remove_cvref_t<T>;
            GenType g;
            // dealias so we print the underlying type ("std::string", "int"),
            // not the local alias name "U".
            constexpr const char *sp =
                std::define_static_string(std::meta::display_string_of(std::meta::dealias(^^U)));
            g.spelling = prettify(sp);
            if constexpr (std::is_void_v<U>) {
                g.kind = "void";
            } else if constexpr (std::is_same_v<U, bool>) {
                g.kind = "boolean";
            } else if constexpr (std::is_same_v<U, std::string>) {
                g.kind = "string";
            } else if constexpr (std::is_arithmetic_v<U>) {
                g.kind    = "number";
                g.integer = std::is_integral_v<U>;
            } else if constexpr (is_func<U>::value) {
                g.kind = "unknown";
            } else if constexpr (is_vec<U>::value) {
                g.kind = "vector";
                g.element.push_back(type_descriptor<typename U::value_type>());
            } else if constexpr (std::is_enum_v<U>) {
                g.kind   = "enum";
                g.object = class_name<U>();
                template for (constexpr auto e : std::define_static_array(
                                  std::meta::enumerators_of(std::meta::dealias(^^U)))) {
                    constexpr const char *en =
                        std::define_static_string(std::meta::identifier_of(e));
                    g.enumerators.push_back(GenEnumerator{en, static_cast<long long>([:e:])});
                }
            } else if constexpr (std::is_class_v<U>) {
                g.kind   = "object";
                g.object = class_name<U>();
            } else {
                g.kind = "unknown";
            }
            return g;
        }

        template <std::meta::info Fn, std::size_t... Is>
        inline std::vector<GenParam> params_impl(std::index_sequence<Is...>) {
            constexpr auto        ps = std::define_static_array(std::meta::parameters_of(Fn));
            std::vector<GenParam> out;
            (out.push_back(GenParam{
                 "arg" + std::to_string(Is),
                 type_descriptor<std::remove_cvref_t<typename[:std::meta::type_of(ps[Is]):]>>()}),
             ...);
            return out;
        }

        template <std::meta::info Fn> inline std::vector<GenParam> params_of() {
            constexpr auto n = std::define_static_array(std::meta::parameters_of(Fn)).size();
            return params_impl<Fn>(std::make_index_sequence<n>{});
        }

        // Exact C++ spelling of a reflected type (cv- and ref-qualifiers kept),
        // prettified only for the libc++ basic_string spelling. Unlike
        // type_descriptor (which strips cvref for the language-neutral kind),
        // this is what a trampoline override signature must reproduce verbatim.
        template <std::meta::info Ty> inline std::string exact_spelling() {
            constexpr const char *s = std::define_static_string(std::meta::display_string_of(Ty));
            return prettify(s);
        }

        template <std::meta::info Fn, std::size_t... Is>
        inline std::vector<std::string> param_cpp_impl(std::index_sequence<Is...>) {
            constexpr auto           ps = std::define_static_array(std::meta::parameters_of(Fn));
            std::vector<std::string> out;
            (out.push_back(exact_spelling<std::meta::type_of(ps[Is])>()), ...);
            return out;
        }

        template <std::meta::info Fn> inline std::vector<std::string> param_cpp_of() {
            constexpr auto n = std::define_static_array(std::meta::parameters_of(Fn)).size();
            return param_cpp_impl<Fn>(std::make_index_sequence<n>{});
        }

        inline std::string num_str(double d); // defined below; used by default_value_str

        // Render a field's default member initializer (read from a default-built
        // instance) to a string, for the kinds that map to a scalar property.
        template <class F> inline std::string default_value_str(const F &v) {
            if constexpr (std::is_same_v<F, bool>) {
                return v ? "1" : "0";
            } else if constexpr (std::is_enum_v<F>) {
                return std::to_string(static_cast<long long>(v));
            } else if constexpr (std::is_integral_v<F>) {
                return std::to_string(v);
            } else if constexpr (std::is_floating_point_v<F>) {
                return num_str(static_cast<double>(v));
            } else if constexpr (std::is_same_v<F, std::string>) {
                return v;
            } else {
                return {}; // vectors / objects — no scalar default
            }
        }

        // Walk visitor that collects member type info into a GenClass. Templated
        // on T so it can read default member initializers from a default instance.
        template <class T> struct IRVisitor {
            GenClass &out;

            template <std::meta::info Fld, auto... Anns> void field(const char *name) {
                GenField gf;
                gf.name = name;
                gf.type = type_descriptor<std::remove_cvref_t<typename[:std::meta::type_of(Fld):]>>();
                gf.is_readonly = ann::has<readonly>(Anns...);
                gf.doc         = ann::get_or<doc>(doc{""}, Anns...).text;
                if constexpr (ann::has<range>(Anns...)) {
                    constexpr auto r = ann::get_or<range>(range{0, 0}, Anns...);
                    gf.range         = GenRange{true, r.min, r.max};
                }
                if constexpr (ann::has<combobox>(Anns...)) {
                    constexpr auto cb = ann::get_or<combobox>(combobox{}, Anns...);
                    for (std::size_t i = 0; i < cb.count; ++i) {
                        gf.choices.push_back(cb.choices[i]);
                    }
                }
                // Default value: read the member from a default-built instance.
                if constexpr (std::is_default_constructible_v<T>) {
                    using F = std::remove_cvref_t<typename[:std::meta::type_of(Fld):]>;
                    T tmp{};
                    gf.default_value = default_value_str<F>(tmp.[:Fld:]);
                }
                // Every annotation, type-erased — backends query what they want.
                (gf.annotations.emplace_back(Anns), ...);
                out.fields.push_back(std::move(gf));
            }

            template <std::meta::info Fn, auto... Anns> void method_instance(const char *name) {
                constexpr auto vs = ann::get_or<virtual_spec>(virtual_spec{}, Anns...);
                push_method<Fn>(name, false, ann::get_or<doc>(doc{""}, Anns...).text,
                                ann::has<virtual_spec>(Anns...), vs);
            }

            template <std::meta::info Fn, auto... Anns> void method_static(const char *name) {
                // static members are never virtual; pass a default virtual_spec.
                push_method<Fn>(name, true, ann::get_or<doc>(doc{""}, Anns...).text, false,
                                virtual_spec{});
            }

            template <std::meta::info Ctor, auto... /*Anns*/> void constructor() {
                out.ctors.push_back(params_of<Ctor>());
            }

          private:
            template <std::meta::info Fn>
            void push_method(const char *name, bool is_static, const char *docstr, bool is_virtual,
                             virtual_spec vs) {
                GenMethod m;
                m.name      = name;
                m.is_static = is_static;
                m.ret =
                    type_descriptor<std::remove_cvref_t<typename[:std::meta::return_type_of(Fn):]>>();
                m.params      = params_of<Fn>();
                m.doc         = docstr;
                m.is_virtual  = is_virtual;
                m.is_pure     = vs.pure;
                m.is_const    = std::meta::is_const(Fn);
                m.is_noexcept = std::meta::is_noexcept(Fn);
                m.ret_cpp     = exact_spelling<std::meta::return_type_of(Fn)>();
                m.param_cpp   = param_cpp_of<Fn>();
                out.methods.push_back(std::move(m));
            }
        };

        // A readable type name for human docs: vectors as `element[]`, everything
        // else its prettified C++ spelling (falling back to the neutral kind).
        inline std::string readable_type(const GenType &t) {
            if (t.kind == "vector") {
                return (t.element.empty() ? std::string("any") : readable_type(t.element.front())) +
                       "[]";
            }
            if (!t.spelling.empty()) {
                return t.spelling;
            }
            if (t.kind == "object" || t.kind == "enum") {
                return t.object.empty() ? "any" : t.object;
            }
            return t.kind;
        }

        // Format a range bound as a clean number (drop a trailing ".0…").
        inline std::string num_str(double d) {
            if (d == static_cast<long long>(d)) {
                return std::to_string(static_cast<long long>(d));
            }
            std::string s = std::to_string(d);
            s.erase(s.find_last_not_of('0') + 1);
            if (!s.empty() && s.back() == '.') {
                s.pop_back();
            }
            return s;
        }

        // The per-class Markdown fragment (heading + field table + methods),
        // rendered from the erased IR. Used as GenClass::doc (README bodies and
        // the markdown backend) and by rosetta::to_markdown<T>(). Mirrors what the
        // former <rosetta/docgen.h> produced, but from GenClass rather than a walk.
        inline std::string class_markdown(const GenClass &gc) {
            std::string out = "# " + gc.name + "\n\n";
            if (!gc.fields.empty()) {
                out += "## Fields\n\n| Name | Type | Description |\n|------|------|-------------|\n";
                for (const auto &f : gc.fields) {
                    std::string desc = f.doc;
                    auto        add  = [&](const std::string &tag) {
                        if (!desc.empty()) {
                            desc += " ";
                        }
                        desc += tag;
                    };
                    if (f.range.has) {
                        add("(range: " + num_str(f.range.min) + ".." + num_str(f.range.max) + ")");
                    }
                    if (!f.choices.empty()) {
                        std::string c = "(choices: ";
                        for (std::size_t i = 0; i < f.choices.size(); ++i) {
                            c += (i ? ", " : "") + f.choices[i];
                        }
                        add(c + ")");
                    }
                    if (f.is_readonly) {
                        add("_(readonly)_");
                    }
                    out += "| `" + f.name + "` | `" + readable_type(f.type) + "` | " + desc + " |\n";
                }
            }
            if (!gc.methods.empty()) {
                out += (gc.fields.empty() ? "" : "\n");
                out += "## Methods\n\n";
                for (const auto &m : gc.methods) {
                    out += "### `";
                    out += (m.is_static ? "static " : "");
                    out += m.name + "(";
                    for (std::size_t i = 0; i < m.params.size(); ++i) {
                        out += (i ? ", " : "") + m.params[i].name + ": " +
                               readable_type(m.params[i].type);
                    }
                    out += ") → " + readable_type(m.ret) + "`\n\n";
                    if (!m.doc.empty()) {
                        out += m.doc + "\n\n";
                    }
                }
            }
            return out;
        }

        // Erase one class to plain data — the only place reflection runs.
        template <typename T> inline GenClass describe() {
            GenClass gc;
            gc.name = class_name<T>();
            // binding_info<T>::header is the #include basename — needed by code
            // backends, but not by render-to-string callers (to_markdown / to_html),
            // which may have no specialization. Use it only when present.
            if constexpr (requires { binding_info<T>::header; }) {
                gc.header = binding_info<T>::header;
            }
            // Carry the out-of-line annotation source so re-walking backends
            // (python / node) can re-emit it into their own TUs — see
            // includes_of(). Empty when the class has no side-car.
            gc.annotations_json = std::string(rosetta::ann_json_source<T>);
            // Every class-level annotation, type-erased — backends query what
            // they want via find_annotation<A>(); the core names none of them.
            template for (constexpr auto a :
                          std::define_static_array(std::meta::annotations_of(^^T))) {
                gc.annotations.emplace_back([:std::meta::constant_of(a):]);
            }
            IRVisitor<T> v{gc};
            walk<T>(v);
            // Render the doc fragment after the walk has filled fields/methods.
            gc.doc = class_markdown(gc);
            return gc;
        }

        // Render an enum's markdown fragment (heading + value table). Used both
        // as the GenEnum::doc (README body) and by the markdown backend.
        inline std::string render_enum_markdown(const GenEnum &ge) {
            std::string s = "# " + ge.name + "\n\n";
            s += "_enum";
            if (!ge.underlying.empty()) {
                s += " : " + ge.underlying;
            }
            s += "_\n\n";
            s += "| Name | Value |\n|------|-------|\n";
            for (const auto &v : ge.values) {
                s += "| `" + v.name + "` | " + std::to_string(v.value) + " |\n";
            }
            return s;
        }

        // Erase one enum to plain data — collects its enumerators via
        // reflection. The companion to describe() for enum pack elements.
        template <typename T> inline GenEnum describe_enum() {
            GenEnum ge;
            ge.name       = class_name<T>();
            ge.header     = binding_info<T>::header;
            ge.underlying = std::define_static_string(
                std::meta::display_string_of(std::meta::underlying_type(^^T)));
            template for (constexpr auto e :
                          std::define_static_array(std::meta::enumerators_of(^^T))) {
                constexpr const char *en = std::define_static_string(std::meta::identifier_of(e));
                ge.values.push_back(GenEnumerator{en, static_cast<long long>([:e:])});
            }
            ge.doc = render_enum_markdown(ge);
            return ge;
        }

        // Build a GenContext from a type pack (no files, no targets) — the same
        // class/enum split generate() does, for the render-to-string helpers.
        template <typename... Ts> inline GenContext make_context(std::string lib) {
            GenContext c;
            c.lib = std::move(lib);
            (
                [&] {
                    if constexpr (std::is_enum_v<Ts>) {
                        c.enums.push_back(describe_enum<Ts>());
                    } else {
                        c.classes.push_back(describe<Ts>());
                    }
                }(),
                ...);
            return c;
        }

    } // namespace gen_detail

} // namespace rosetta

// -------- built-in backends (one file each) --------
// Each defines its templates + a gen_detail::*Backend, using the shared
// render helpers above. New backends register the same way (see
// docs/EXTENDING_BACKEND.md) without touching generate().
#include <rosetta/backends/html_backend.h>
#include <rosetta/backends/json_backend.h>
#include <rosetta/backends/julia_backend.h>
#include <rosetta/backends/markdown_backend.h>
#include <rosetta/backends/node_backend.h>
#include <rosetta/backends/openapi_backend.h>
#include <rosetta/backends/paraview_backend.h>
#include <rosetta/backends/python_backend.h>
#include <rosetta/backends/rest_backend.h>
#include <rosetta/backends/typescript_backend.h>
#include <rosetta/backends/wasm_backend.h>

namespace rosetta {

    // -------- backend registry --------

    inline std::map<std::string, std::shared_ptr<Backend>> &backend_registry() {
        static std::map<std::string, std::shared_ptr<Backend>> reg = [] {
            std::map<std::string, std::shared_ptr<Backend>> m;
            m["python"]     = std::make_shared<gen_detail::PythonBackend>();
            m["node"]       = std::make_shared<gen_detail::NodeBackend>();
            m["julia"]      = std::make_shared<gen_detail::JuliaBackend>();
            m["rest"]       = std::make_shared<gen_detail::RestBackend>();
            m["wasm"]       = std::make_shared<gen_detail::WasmBackend>();
            m["typescript"] = std::make_shared<gen_detail::TypeScriptBackend>();
            m["markdown"]   = std::make_shared<gen_detail::MarkdownBackend>();
            m["html"]       = std::make_shared<gen_detail::HtmlBackend>();
            m["json"]       = std::make_shared<gen_detail::JsonBackend>();
            m["openapi"]    = std::make_shared<gen_detail::OpenApiBackend>();
            m["paraview"]   = std::make_shared<gen_detail::ParaViewBackend>();
            return m;
        }();
        return reg;
    }

    inline void register_backend(std::string lang, std::shared_ptr<Backend> backend) {
        backend_registry()[std::move(lang)] = std::move(backend);
    }

    // Erase one free function (named by its reflection F) to plain data. Called
    // from the generated driver, which splices `^^name` for each manifest-listed
    // function. `qualified` is the C++ spelling backends emit for `&fn`; `doc`
    // comes from the manifest (free functions carry no in-source annotation, so
    // user headers stay untouched).
    template <std::meta::info F>
    inline GenFunction make_function(const char *qualified, const char *header,
                                     const char *doc) {
        GenFunction gf;
        gf.name      = std::define_static_string(std::meta::identifier_of(F));
        gf.qualified = qualified;
        gf.header    = header;
        gf.ret       = gen_detail::type_descriptor<
            std::remove_cvref_t<typename[:std::meta::return_type_of(F):]>>();
        gf.params = gen_detail::params_of<F>();
        gf.doc    = doc;
        return gf;
    }

    template <typename... Ts> inline void generate(const GenerateOptions &opt) {
        // Erase the type pack into plain data once; backends do no reflection.
        // Enum pack elements go to `enums`, everything else to `classes`.
        std::vector<GenClass> classes;
        std::vector<GenEnum>  enums;
        (
            [&] {
                if constexpr (std::is_enum_v<Ts>)
                    enums.push_back(gen_detail::describe_enum<Ts>());
                else {
                    classes.push_back(gen_detail::describe<Ts>());
                }
            }(),
            ...);

        for (const TargetSpec &t : opt.targets) {
            auto &reg = backend_registry();
            auto  it  = reg.find(t.lang);
            if (it == reg.end() || !it->second) {
                std::fprintf(
                    stderr,
                    "rosetta::generate: no backend registered for target '%s' — skipped\n",
                    t.lang.c_str());
                continue;
            }
            it->second->emit(GenContext{opt.out_dir, t.name, classes, enums,
                                        opt.functions, opt.user_include.string(),
                                        opt.rosetta_include.string()});
        }
    }

} // namespace rosetta
