// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Julia (CxxWrap / jlcxx) generation backend. Included by inline/generate.hxx,
// which provides the shared render helpers (render_meta / render_source /
// readme / write_file) this file relies on.
//
// Like the Python and Node backends, this only emits a thin driver: the
// generated `auto_jlcxx.cpp` includes <rosetta/visitors/julia_visitor.h> and
// delegates every type/enum/function to the visitor's bind_julia* entry
// points — all the real binding logic lives in the visitor.

#pragma once

namespace rosetta {
    namespace gen_detail {

        constexpr std::string_view JULIA_CPP =
            R"CPP(// Generated by rosetta::generate — do not edit by hand.
{{INCLUDES}}#include <rosetta/visitors/julia_visitor.h>

// CxxWrap.jl loads this entry point (default symbol `define_julia_module`)
// from Julia via `@wrapmodule(() -> libpath)`.
JLCXX_MODULE define_julia_module(jlcxx::Module &mod) {
{{BINDINGS}}}
)CPP";

        constexpr std::string_view JULIA_CMAKE = R"CMK({{HEADER_BLOCK}}
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

# Locate JlCxx (from libcxxwrap-julia / CxxWrap.jl). If it isn't hinted via
# JlCxx_DIR or CMAKE_PREFIX_PATH, ask Julia's CxxWrap for the prefix that
# ships the JlCxx CMake package. --startup-file=no keeps a user startup.jl
# from polluting the captured path.
if(NOT JlCxx_DIR AND NOT DEFINED CMAKE_PREFIX_PATH)
    execute_process(
        COMMAND julia --startup-file=no -e "using CxxWrap; print(CxxWrap.prefix_path())"
        OUTPUT_VARIABLE CXXWRAP_PREFIX
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(CXXWRAP_PREFIX)
        set(CMAKE_PREFIX_PATH "${CXXWRAP_PREFIX}")
    endif()
endif()
find_package(JlCxx REQUIRED)

add_library({{LIB}} SHARED auto_jlcxx.cpp)

target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

target_link_libraries({{LIB}} PRIVATE
    JlCxx::cxxwrap_julia
    JlCxx::cxxwrap_julia_stl)

target_compile_options({{LIB}} PRIVATE
    -freflection -freflection-latest -fexperimental-library -fannotation-attributes)

target_link_options({{LIB}} PRIVATE
    -nostdlib++ -L${CLANG_P2996_ROOT}/lib -Wl,-rpath,${CLANG_P2996_ROOT}/lib
    -lc++ -lc++abi)

add_custom_command(TARGET {{LIB}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        $<TARGET_FILE:{{LIB}}>
        ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
)CMK";

        struct JuliaBackend : Backend {
            void emit(const GenContext &c) const override {
                std::string binds;
                // Enums first so class fields/methods can resolve them.
                for (const auto &e : c.enums) {
                    binds += "    rosetta::bind_julia_enum<" + e.name + ">(mod, \"" + e.name +
                             "\");\n";
                }
                for (const auto &k : c.classes) {
                    binds +=
                        "    rosetta::bind_julia<" + k.name + ">(mod, \"" + k.name + "\");\n";
                }
                for (const auto &f : c.functions) {
                    binds += "    rosetta::bind_julia_function<^^" + f.qualified + ">(mod, \"" +
                             f.name + "\");\n";
                }
                auto dir = c.out_dir / "julia";
                write_file(dir / "auto_jlcxx.cpp", render_source(JULIA_CPP, c, binds));
                write_file(dir / "CMakeLists.txt", render_meta(JULIA_CMAKE, c));
                write_file(dir / "README.md", readme("julia", c));
            }
        };

    } // namespace gen_detail
} // namespace rosetta
