// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Markdown documentation backend — emits a single `.md` reference describing
// the bound classes (a companion to the runtime bindings). Like the TypeScript
// backend, this is a *pure-data* backend: it consumes the reflection IR that
// `generate` erases into GenClass and renders text — no C++ is compiled. Each
// class's `doc` already holds its `generate_markdown<T>()` fragment, so this
// backend stitches those into one library reference. Included by
// inline/generate.hxx.

#pragma once

namespace rosetta {
    namespace gen_detail {

        struct MarkdownBackend : Backend {
            void emit(const GenContext &c) const override {
                std::string out = "<!-- Generated by rosetta::generate — do not edit by hand. -->\n";
                out += "# `" + c.lib + "` API reference\n\n";

                // Table of contents — one bullet per class, linking to its
                // section. GitHub anchors lowercase the heading text.
                out += "## Contents\n\n";
                for (const auto &k : c.classes)
                    out += "- [" + k.name + "](#" + k.name + ")\n";
                out += "\n";

                // Each class's per-class markdown (its `# <Name>` heading plus
                // Fields / Methods sections), separated by a horizontal rule.
                for (std::size_t i = 0; i < c.classes.size(); ++i) {
                    if (i)
                        out += "\n---\n\n";
                    out += c.classes[i].doc;
                    if (!out.empty() && out.back() != '\n')
                        out += "\n";
                }

                write_file(c.out_dir / "markdown" / (c.lib + ".md"), out);
            }
        };

    } // namespace gen_detail
} // namespace rosetta
