// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Markdown documentation backend — emits a single `.md` reference describing
// the bound classes (a companion to the runtime bindings). Like the TypeScript
// backend, this is a *pure-data* backend: it consumes the reflection IR that
// `generate` erases into GenClass and renders text — no C++ is compiled. Each
// class's `doc` already holds its `generate_markdown<T>()` fragment, so this
// backend stitches those into one library reference. Included by
// inline/generate.hxx.

#pragma once

namespace rosetta {
    namespace gen_detail {

        struct MarkdownBackend : Backend {
            void emit(const GenContext &c) const override {
                std::string out = "<!-- Generated by rosetta::generate — do not edit by hand. -->\n";
                out += "# `" + c.lib + "` API reference\n\n";

                // Table of contents — one bullet per class then per enum,
                // linking to its section. GitHub anchors lowercase the heading.
                out += "## Contents\n\n";
                for (const auto &k : c.classes)
                    out += "- [" + k.name + "](#" + k.name + ")\n";
                for (const auto &e : c.enums)
                    out += "- [" + e.name + "](#" + e.name + ") _(enum)_\n";
                out += "\n";

                // Each class's, then each enum's, per-entity markdown fragment
                // (a `# <Name>` heading plus its body), separated by rules.
                bool first = true;
                auto section = [&](const std::string &doc) {
                    if (!first)
                        out += "\n---\n\n";
                    first = false;
                    out += doc;
                    if (!out.empty() && out.back() != '\n')
                        out += "\n";
                };
                for (const auto &k : c.classes)
                    section(k.doc);
                for (const auto &e : c.enums)
                    section(e.doc);

                write_file(c.out_dir / "markdown" / (c.lib + ".md"), out);
            }
        };

    } // namespace gen_detail
} // namespace rosetta
