// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Python (pybind11) generation backend. Included by inline/generate.hxx,
// which provides the shared render helpers (render_meta / render_source /
// readme / write_file) this file relies on.

#pragma once

namespace rosetta {
    namespace gen_detail {

        constexpr std::string_view PY_CPP =
            R"CPP(// Generated by rosetta::generate — do not edit by hand.
{{INCLUDES}}#include <rosetta/visitors/python_visitor.h>

PYBIND11_MODULE({{LIB}}, m) {
    m.doc() = "Auto-generated bindings for {{LIB}}.";
{{BINDINGS}}}
)CPP";

        constexpr std::string_view PY_CMAKE = R"CMK({{HEADER_BLOCK}}
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

execute_process(
    COMMAND python3 -c "import sys; print(sys.executable)"
    OUTPUT_VARIABLE Python_EXECUTABLE
    OUTPUT_STRIP_TRAILING_WHITESPACE)
set(Python3_EXECUTABLE "${Python_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(PYBIND11_FINDPYTHON ON)

if(NOT pybind11_DIR)
    execute_process(
        COMMAND ${Python_EXECUTABLE} -m pybind11 --cmakedir
        OUTPUT_VARIABLE pybind11_DIR
        OUTPUT_STRIP_TRAILING_WHITESPACE)
endif()
find_package(pybind11 REQUIRED CONFIG)

pybind11_add_module({{LIB}} NO_EXTRAS auto_pybind.cpp)

target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

target_compile_options({{LIB}} PRIVATE
    -freflection -freflection-latest -fexperimental-library -fannotation-attributes)

target_link_options({{LIB}} PRIVATE
    -nostdlib++ -L${CLANG_P2996_ROOT}/lib -Wl,-rpath,${CLANG_P2996_ROOT}/lib
    -lc++ -lc++abi)

add_custom_command(TARGET {{LIB}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        $<TARGET_FILE:{{LIB}}>
        ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
)CMK";

        struct PythonBackend : Backend {
            void emit(const GenContext &c) const override {
                std::string binds;
                // Enums first so class fields/methods can resolve them.
                for (const auto &e : c.enums)
                    binds += "    rosetta::bind_pybind_enum<" + e.name + ">(m, \"" + e.name +
                             "\");\n";
                for (const auto &k : c.classes)
                    binds += "    rosetta::bind_pybind<" + k.name + ">(m, \"" + k.name + "\");\n";
                auto dir = c.out_dir / "python";
                write_file(dir / "auto_pybind.cpp", render_source(PY_CPP, c, binds));
                write_file(dir / "CMakeLists.txt", render_meta(PY_CMAKE, c));
                write_file(dir / "README.md", readme("python", c));
            }
        };

    } // namespace gen_detail
} // namespace rosetta
