// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// C# generation backend. Included by inline/generate.hxx, which provides the
// shared render helpers (subst / includes_of / render_meta / readme /
// write_file) and the jsonable_* predicates this file relies on.
//
// Two artifacts work together:
//   - auto_csharp.cpp: a C++26 shim that registers each reflected type with the
//     runtime in <rosetta/visitors/csharp_visitor.h> and exports a flat C ABI
//     (rosetta_csharp_*). Built into a shared library by the generated CMake.
//   - <Lib>.cs: idiomatic C# wrappers rendered from the reflected IR. Each class
//     is a handle (an integer id into the native store); property/method access
//     is a JSON round-trip through the C ABI via P/Invoke. This part is pure-data
//     templating — no C++ is involved.
//
// The C# surface matches the runtime's: scalars, bool, string, enums (by name),
// and List<…> of those. Members using any other type are skipped on both sides
// (jsonable_type / jsonable_method here mirror cs::supported in the runtime), so
// the wrapper never references a C ABI operation that wasn't registered.

#pragma once

namespace rosetta {
    namespace gen_detail {

        constexpr std::string_view CS_CPP =
            R"CPP(// Generated by rosetta::generate — do not edit by hand.
{{INCLUDES}}#include <rosetta/visitors/csharp_visitor.h>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <string>

namespace {

void register_all() {
{{BINDINGS}}}

void ensure_registered() {
    static std::once_flag once;
    std::call_once(once, [] { register_all(); });
}

// Copy a std::string into a malloc'd C string; the C# side releases it via
// rosetta_csharp_free. Returns nullptr only on allocation failure.
char *dup_cstr(const std::string &s) {
    char *p = static_cast<char *>(std::malloc(s.size() + 1));
    if (p) {
        std::memcpy(p, s.c_str(), s.size() + 1);
    }
    return p;
}

} // namespace

extern "C" {

ROSETTA_CS_EXPORT int rosetta_csharp_create(const char *type, const char *args) {
    ensure_registered();
    return rosetta::cs::api_create(type, args);
}

ROSETTA_CS_EXPORT int rosetta_csharp_destroy(const char *type, int id) {
    ensure_registered();
    return rosetta::cs::api_destroy(type, id) ? 1 : 0;
}

ROSETTA_CS_EXPORT char *rosetta_csharp_get_field(const char *type, int id, const char *field) {
    ensure_registered();
    return dup_cstr(rosetta::cs::api_get(type, id, field));
}

ROSETTA_CS_EXPORT char *rosetta_csharp_set_field(const char *type, int id, const char *field,
                                                 const char *value) {
    ensure_registered();
    return dup_cstr(rosetta::cs::api_set(type, id, field, value));
}

ROSETTA_CS_EXPORT char *rosetta_csharp_call_method(const char *type, int id, const char *method,
                                                   const char *args) {
    ensure_registered();
    return dup_cstr(rosetta::cs::api_call(type, id, method, args));
}

ROSETTA_CS_EXPORT char *rosetta_csharp_call_static(const char *type, const char *method,
                                                   const char *args) {
    ensure_registered();
    return dup_cstr(rosetta::cs::api_scall(type, method, args));
}

ROSETTA_CS_EXPORT char *rosetta_csharp_call_function(const char *name, const char *args) {
    ensure_registered();
    return dup_cstr(rosetta::cs::api_function(name, args));
}

ROSETTA_CS_EXPORT char *rosetta_csharp_enum_values(const char *type) {
    ensure_registered();
    return dup_cstr(rosetta::cs::api_enum(type));
}

ROSETTA_CS_EXPORT void rosetta_csharp_free(char *p) { std::free(p); }

} // extern "C"
)CPP";

        constexpr std::string_view CS_CMAKE = R"CMK({{HEADER_BLOCK}}
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

include(FetchContent)
FetchContent_Declare(json
    GIT_REPOSITORY https://github.com/nlohmann/json.git
    GIT_TAG        v3.11.3)
FetchContent_MakeAvailable(json)

# A plain shared library: the .NET wrapper reaches it through P/Invoke. Only the
# rosetta_csharp_* entry points are exported (visibility hidden by default).
add_library({{LIB}} SHARED auto_csharp.cpp)
set_target_properties({{LIB}} PROPERTIES
    POSITION_INDEPENDENT_CODE ON
    CXX_VISIBILITY_PRESET hidden
    VISIBILITY_INLINES_HIDDEN ON)

target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})
{{USER_LIB_BLOCK}}
target_link_libraries({{LIB}} PRIVATE nlohmann_json::nlohmann_json)

target_compile_options({{LIB}} PRIVATE
    {{REFLECTION_FLAGS}})

target_link_options({{LIB}} PRIVATE
    {{STDLIB_LINK}})
)CMK";

        // C#-specific README: the two-part build (native shim + .NET assembly)
        // and how the runtime loader finds the shared library are not obvious, so
        // unlike most backends this one doesn't fall back to the generic readme().
        constexpr std::string_view CS_README = R"MD(# `{{LIB}}` (csharp)

Auto-generated C# bindings. Two pieces work together:

- **`auto_csharp.cpp`** → a native shared library exposing a flat C ABI
  (`rosetta_csharp_*`). Built with the C++26 reflection toolchain.
- **`{{LIB}}.cs`** → idiomatic C# wrappers. Each class is a handle into the
  native instance store; property and method access is a JSON round-trip through
  the C ABI via P/Invoke (`System.Text.Json` does the (de)serialisation).

## Build

```sh
# 1. the native library (produces lib{{LIB}}.{dylib,so} / {{LIB}}.dll)
cmake -S . -B build && cmake --build build

# 2. the .NET assembly
dotnet build {{LIB}}.csproj
```

## Run

The .NET loader must find the native library at run time. Point it at the CMake
build dir (or copy `lib{{LIB}}.*` next to your executable):

```sh
# macOS
DYLD_LIBRARY_PATH=build dotnet run
# Linux
LD_LIBRARY_PATH=build dotnet run
```

## Use

```csharp
using {{NS}};

using var p = new Person();   // IDisposable — frees the native instance
p.name = "Alice";
System.Console.WriteLine(p.greet("Hi"));
```

Boundary types: scalars, `bool`, `string`, enums (by name), and `List<…>` of
those. Members using any other type are omitted from both sides.

)MD";

        constexpr std::string_view CS_CSPROJ = R"CSPROJ(<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>{{LIB}}</AssemblyName>
    <RootNamespace>{{NS}}</RootNamespace>
  </PropertyGroup>

</Project>
)CSPROJ";

        // -------- C# rendering helpers --------

        // Sanitise an arbitrary library name into a C# identifier usable as a
        // namespace (letters / digits / underscore; must not start with a digit).
        inline std::string cs_ident(const std::string &s) {
            auto is_alnum = [](char ch) {
                return (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
                       (ch >= '0' && ch <= '9');
            };
            auto is_digit = [](char ch) { return ch >= '0' && ch <= '9'; };
            std::string out;
            for (char ch : s) {
                out += (is_alnum(ch) ? ch : '_');
            }
            if (out.empty() || is_digit(out.front())) {
                out.insert(out.begin(), '_');
            }
            return out;
        }

        // Render a neutral GenType as the C# type the wrapper marshals it to.
        // Only ever called for jsonable types; the fallback is defensive.
        inline std::string cs_type(const GenType &t) {
            if (t.kind == "boolean") {
                return "bool";
            }
            if (t.kind == "string") {
                return "string";
            }
            if (t.kind == "number") {
                return t.integer ? "long" : "double";
            }
            if (t.kind == "enum") {
                return t.object.empty() ? "long" : t.object;
            }
            if (t.kind == "vector") {
                return "System.Collections.Generic.List<" +
                       (t.element.empty() ? std::string("object") : cs_type(t.element.front())) +
                       ">";
            }
            return "object";
        }

        // "double arg0, double arg1"
        inline std::string cs_param_sig(const std::vector<GenParam> &ps) {
            std::string s;
            for (std::size_t i = 0; i < ps.size(); ++i) {
                s += (i ? ", " : "") + cs_type(ps[i].type) + " " + ps[i].name;
            }
            return s;
        }

        // "arg0, arg1" — the argument list forwarded to Rt.Args(...).
        inline std::string cs_arg_names(const std::vector<GenParam> &ps) {
            std::string s;
            for (std::size_t i = 0; i < ps.size(); ++i) {
                s += (i ? ", " : "") + ps[i].name;
            }
            return s;
        }

        inline bool cs_ctor_jsonable(const std::vector<GenParam> &ps) {
            for (const auto &p : ps) {
                if (!jsonable_type(p.type)) {
                    return false;
                }
            }
            return true;
        }

        // The fixed runtime helpers (Native P/Invoke surface + Rt marshalling +
        // exception type), emitted once per module.
        inline std::string cs_runtime(const GenContext &c) {
            const std::string lib = c.lib;
            std::string       s;
            s += "    public class RosettaException : System.Exception {\n";
            s += "        public RosettaException(string message) : base(message) { }\n";
            s += "    }\n\n";

            s += "    internal static class Native {\n";
            s += "        private const string LIB = \"" + lib + "\";\n";
            auto str = [](const char *n) {
                return std::string("[System.Runtime.InteropServices.MarshalAs("
                                   "System.Runtime.InteropServices.UnmanagedType.LPUTF8Str)] string ") +
                       n;
            };
            const std::string dll = "        [System.Runtime.InteropServices.DllImport(LIB, "
                                    "CallingConvention = "
                                    "System.Runtime.InteropServices.CallingConvention.Cdecl)]\n";
            s += dll + "        internal static extern int rosetta_csharp_create(" + str("type") +
                 ", " + str("args") + ");\n";
            s += dll + "        internal static extern int rosetta_csharp_destroy(" + str("type") +
                 ", int id);\n";
            s += dll +
                 "        internal static extern System.IntPtr rosetta_csharp_get_field(" +
                 str("type") + ", int id, " + str("field") + ");\n";
            s += dll +
                 "        internal static extern System.IntPtr rosetta_csharp_set_field(" +
                 str("type") + ", int id, " + str("field") + ", " + str("value") + ");\n";
            s += dll +
                 "        internal static extern System.IntPtr rosetta_csharp_call_method(" +
                 str("type") + ", int id, " + str("method") + ", " + str("args") + ");\n";
            s += dll +
                 "        internal static extern System.IntPtr rosetta_csharp_call_static(" +
                 str("type") + ", " + str("method") + ", " + str("args") + ");\n";
            s += dll +
                 "        internal static extern System.IntPtr rosetta_csharp_call_function(" +
                 str("name") + ", " + str("args") + ");\n";
            s += dll +
                 "        internal static extern System.IntPtr rosetta_csharp_enum_values(" +
                 str("type") + ");\n";
            s += dll +
                 "        internal static extern void rosetta_csharp_free(System.IntPtr p);\n";
            s += "    }\n\n";

            s += R"CS(    internal static class Rt {
        // Enums cross the boundary as their underlying integer (the native side
        // marshals them that way), which is System.Text.Json's default for
        // C# enums — so no custom converter is needed.
        private static readonly System.Text.Json.JsonSerializerOptions Opts =
            new System.Text.Json.JsonSerializerOptions();

        private static string Take(System.IntPtr p) {
            if (p == System.IntPtr.Zero) return "";
            string s = System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? "";
            Native.rosetta_csharp_free(p);
            return s;
        }

        // Parse the {"ok":…,"value":…,"error":…} envelope, throwing on failure.
        private static System.Text.Json.JsonElement Unwrap(System.IntPtr p) {
            string env = Take(p);
            using var doc = System.Text.Json.JsonDocument.Parse(env);
            var root = doc.RootElement;
            if (!root.GetProperty("ok").GetBoolean()) {
                string msg = root.TryGetProperty("error", out var e) ? (e.GetString() ?? "error") : "error";
                throw new RosettaException(msg);
            }
            return root.GetProperty("value").Clone();
        }

        internal static T Get<T>(System.IntPtr p) =>
            System.Text.Json.JsonSerializer.Deserialize<T>(Unwrap(p).GetRawText(), Opts)!;
        internal static void Void(System.IntPtr p) { Unwrap(p); }
        internal static string Args(params object?[] a) =>
            System.Text.Json.JsonSerializer.Serialize(a, Opts);
        internal static string Ser(object? v) =>
            System.Text.Json.JsonSerializer.Serialize(v, Opts);
        internal static int New(string type, string args) {
            int id = Native.rosetta_csharp_create(type, args);
            if (id < 0) throw new RosettaException("failed to construct " + type);
            return id;
        }
    }

)CS";
            return s;
        }

        // One handle-backed wrapper class.
        inline std::string cs_class(const GenClass &k) {
            std::string s;
            if (!k.doc.empty()) {
                s += "    // " + k.name + "\n";
            }
            s += "    public sealed class " + k.name + " : System.IDisposable {\n";
            s += "        private int _id;\n";
            s += "        private const string _t = \"" + k.name + "\";\n\n";

            // Constructors. Dedupe by C# signature so two C++ ctors that erase to
            // the same arity/types don't produce a duplicate member.
            std::vector<std::string> seen_sigs;
            auto                     emit_ctor = [&](const std::vector<GenParam> &ps) {
                const std::string sig = cs_param_sig(ps);
                for (const auto &s2 : seen_sigs) {
                    if (s2 == sig) {
                        return;
                    }
                }
                seen_sigs.push_back(sig);
                const std::string args =
                    ps.empty() ? std::string("\"[]\"") : "Rt.Args(" + cs_arg_names(ps) + ")";
                s += "        public " + k.name + "(" + sig + ") { _id = Rt.New(_t, " + args +
                     "); }\n";
            };
            if (k.is_default_constructible) {
                emit_ctor({});
            }
            for (const auto &ct : k.ctors) {
                if (!ct.empty() && cs_ctor_jsonable(ct)) {
                    emit_ctor(ct);
                }
            }
            if (seen_sigs.empty()) {
                // No JSON-marshalable constructor — block the implicit public
                // parameterless ctor so a broken (id 0) instance can't be made.
                s += "        private " + k.name +
                     "() { } // no JSON-marshalable constructor\n";
            }

            s += "\n        public void Dispose() {\n";
            s += "            if (_id > 0) { Native.rosetta_csharp_destroy(_t, _id); _id = 0; }\n";
            s += "            System.GC.SuppressFinalize(this);\n";
            s += "        }\n";
            s += "        ~" + k.name +
                 "() { if (_id > 0) Native.rosetta_csharp_destroy(_t, _id); }\n";

            // Fields → properties.
            for (const auto &f : k.fields) {
                if (!jsonable_type(f.type)) {
                    continue;
                }
                const std::string ty = cs_type(f.type);
                if (!f.doc.empty()) {
                    s += "\n        /// <summary>" + f.doc + "</summary>";
                }
                s += "\n        public " + ty + " " + f.name + " {\n";
                s += "            get => Rt.Get<" + ty +
                     ">(Native.rosetta_csharp_get_field(_t, _id, \"" + f.name + "\"));\n";
                if (!f.is_readonly) {
                    s += "            set => Rt.Void(Native.rosetta_csharp_set_field(_t, _id, \"" +
                         f.name + "\", Rt.Ser(value)));\n";
                }
                s += "        }\n";
            }

            // Methods.
            for (const auto &m : k.methods) {
                if (!jsonable_method(m)) {
                    continue;
                }
                const std::string sig    = cs_param_sig(m.params);
                const std::string names  = cs_arg_names(m.params);
                const std::string argexp = "Rt.Args(" + names + ")";
                if (!m.doc.empty()) {
                    s += "\n        /// <summary>" + m.doc + "</summary>";
                }
                s += "\n        public " + std::string(m.is_static ? "static " : "");
                const std::string callexpr =
                    m.is_static
                        ? "Native.rosetta_csharp_call_static(_t, \"" + m.name + "\", " + argexp + ")"
                        : "Native.rosetta_csharp_call_method(_t, _id, \"" + m.name + "\", " +
                              argexp + ")";
                if (m.ret.kind == "void") {
                    s += "void " + m.name + "(" + sig + ") => Rt.Void(" + callexpr + ");\n";
                } else {
                    s += cs_type(m.ret) + " " + m.name + "(" + sig + ") => Rt.Get<" +
                         cs_type(m.ret) + ">(" + callexpr + ");\n";
                }
            }

            s += "    }\n\n";
            return s;
        }

        inline std::string csharp_wrapper(const GenContext &c) {
            const std::string ns = cs_ident(c.lib);
            std::string       s  = "// Generated by rosetta::generate — do not edit by hand.\n";
            s += "#nullable enable\n\n";
            s += "namespace " + ns + " {\n\n";

            for (const auto &e : c.enums) {
                if (!e.doc.empty()) {
                    s += "    // " + e.name + "\n";
                }
                s += "    public enum " + e.name + " {\n";
                for (const auto &v : e.values) {
                    s += "        " + v.name + " = " + std::to_string(v.value) + ",\n";
                }
                s += "    }\n\n";
            }

            s += cs_runtime(c);

            for (const auto &k : c.classes) {
                s += cs_class(k);
            }

            // Free functions → a static facade class.
            bool any_fn = false;
            for (const auto &f : c.functions) {
                if (jsonable_function(f)) {
                    any_fn = true;
                    break;
                }
            }
            if (any_fn) {
                s += "    public static class " + cs_ident(c.lib) + "Functions {\n";
                for (const auto &f : c.functions) {
                    if (!jsonable_function(f)) {
                        continue;
                    }
                    const std::string argexp = "Rt.Args(" + cs_arg_names(f.params) + ")";
                    const std::string call =
                        "Native.rosetta_csharp_call_function(\"" + f.name + "\", " + argexp + ")";
                    if (!f.doc.empty()) {
                        s += "        /// <summary>" + f.doc + "</summary>\n";
                    }
                    s += "        public static ";
                    if (f.ret.kind == "void") {
                        s += "void " + f.name + "(" + cs_param_sig(f.params) + ") => Rt.Void(" +
                             call + ");\n";
                    } else {
                        s += cs_type(f.ret) + " " + f.name + "(" + cs_param_sig(f.params) +
                             ") => Rt.Get<" + cs_type(f.ret) + ">(" + call + ");\n";
                    }
                }
                s += "    }\n\n";
            }

            s += "}\n";
            return s;
        }

        // The register_all() body: one bind_csharp* call per exposed entity.
        inline std::string csharp_registrations(const GenContext &c) {
            std::string s;
            for (const auto &e : c.enums) {
                s += "    rosetta::bind_csharp_enum<" + e.name + ">(\"" + e.name + "\");\n";
            }
            for (const auto &k : c.classes) {
                s += "    rosetta::bind_csharp<" + k.name + ">(\"" + k.name + "\");\n";
            }
            for (const auto &f : c.functions) {
                s += "    rosetta::bind_csharp_function<^^" + f.qualified + ">(\"" + f.name +
                     "\");\n";
            }
            return s;
        }

        inline std::string csharp_source(const GenContext &c) {
            // includes_of() also emits the `using namespace` a namespaced user
            // library needs (so unqualified bind_csharp<T> resolves).
            return subst(CS_CPP, {{"INCLUDES", includes_of(c)},
                                  {"BINDINGS", csharp_registrations(c)}});
        }

        inline std::string CSharpBackend::render(const GenContext &c) const {
            return csharp_source(c);
        }

        inline void CSharpBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "csharp";
            write_file(dir / "auto_csharp.cpp", csharp_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(CS_CMAKE, c));
            write_file(dir / (c.lib + ".cs"), csharp_wrapper(c));
            write_file(dir / (c.lib + ".csproj"),
                       subst(CS_CSPROJ, {{"LIB", c.lib}, {"NS", cs_ident(c.lib)}}));
            // The standard header/usage, then the per-class reference docs.
            const std::string doc =
                subst(CS_README, {{"LIB", c.lib}, {"NS", cs_ident(c.lib)}}) +
                readme_body_of(c.classes);
            write_file(dir / "README.md", doc);
        }

    } // namespace gen_detail
} // namespace rosetta
