// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Expanded (reflection-free) Java backend. Included by inline/generate.hxx after
// java_backend.h (reuses java_native / java_runtime_src / java_class / java_enum
// / java_functions / java_pkg / JAVA_POM / JAVA_README), python_expanded_backend.h
// (reuses qualify_std) and csharp_expanded_backend.h (reuses csx_double_lit),
// plus the shared render helpers (jsonable_*, render_meta, write_file).
//
// The generated auto_java.cpp registers every field / method / constructor by
// pointer, so the runtime deduces the marshalled types from the pointer type —
// no reflection at the target's compile time. The Java side is byte-identical to
// the thin backend's.

#pragma once

namespace rosetta {
    namespace gen_detail {

        // Stock-toolchain CMake: C++20 (member-pointer + class-type NTTPs for the
        // runtime's get_field<&T::f> / fixed_str), the user's headers, and
        // rosetta's include dir purely for the reflection-free java_runtime.h.
        // No clang-p2996, no -freflection, no -nostdlib++.
        constexpr std::string_view JVX_CMAKE =
            R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# Plain shared library reached from Java via the Foreign Function & Memory API.
# NO C++26, NO reflection; rosetta's include dir is on the path only for the
# header-only java_runtime.h.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include(FetchContent)
FetchContent_Declare(json
    GIT_REPOSITORY https://github.com/nlohmann/json.git
    GIT_TAG        v3.11.3)
FetchContent_MakeAvailable(json)

add_library({{LIB}} SHARED auto_java.cpp)
set_target_properties({{LIB}} PROPERTIES
    POSITION_INDEPENDENT_CODE ON
    CXX_VISIBILITY_PRESET hidden
    VISIBILITY_INLINES_HIDDEN ON)

target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

target_link_libraries({{LIB}} PRIVATE nlohmann_json::nlohmann_json)
)CMK";

        // The fixed part of the native shim: ensure_registered + dup_cstr + the
        // exported C ABI. Identical to the thin backend's (only register_all and
        // the includes differ between the two), so both speak the same protocol.
        constexpr std::string_view JVX_ABI = R"CPP(
void ensure_registered() {
    static std::once_flag once;
    std::call_once(once, [] { register_all(); });
}

// Copy a std::string into a malloc'd C string; the Java side releases it via
// rosetta_java_free. Returns nullptr only on allocation failure.
char *dup_cstr(const std::string &s) {
    char *p = static_cast<char *>(std::malloc(s.size() + 1));
    if (p) {
        std::memcpy(p, s.c_str(), s.size() + 1);
    }
    return p;
}

} // namespace

extern "C" {

ROSETTA_JAVA_EXPORT int rosetta_java_create(const char *type, const char *args) {
    ensure_registered();
    return rosetta::jvm::api_create(type, args);
}

ROSETTA_JAVA_EXPORT int rosetta_java_destroy(const char *type, int id) {
    ensure_registered();
    return rosetta::jvm::api_destroy(type, id) ? 1 : 0;
}

ROSETTA_JAVA_EXPORT char *rosetta_java_get_field(const char *type, int id, const char *field) {
    ensure_registered();
    return dup_cstr(rosetta::jvm::api_get(type, id, field));
}

ROSETTA_JAVA_EXPORT char *rosetta_java_set_field(const char *type, int id, const char *field,
                                                 const char *value) {
    ensure_registered();
    return dup_cstr(rosetta::jvm::api_set(type, id, field, value));
}

ROSETTA_JAVA_EXPORT char *rosetta_java_call_method(const char *type, int id, const char *method,
                                                   const char *args) {
    ensure_registered();
    return dup_cstr(rosetta::jvm::api_call(type, id, method, args));
}

ROSETTA_JAVA_EXPORT char *rosetta_java_call_static(const char *type, const char *method,
                                                   const char *args) {
    ensure_registered();
    return dup_cstr(rosetta::jvm::api_scall(type, method, args));
}

ROSETTA_JAVA_EXPORT char *rosetta_java_call_function(const char *name, const char *args) {
    ensure_registered();
    return dup_cstr(rosetta::jvm::api_function(name, args));
}

ROSETTA_JAVA_EXPORT char *rosetta_java_enum_values(const char *type) {
    ensure_registered();
    return dup_cstr(rosetta::jvm::api_enum(type));
}

ROSETTA_JAVA_EXPORT void rosetta_java_free(char *p) { std::free(p); }

} // extern "C"
)CPP";

        // One class, expanded into an explicit TypeOps registration block.
        inline std::string jvx_class(const GenClass &k) {
            const std::string t = k.name;
            std::string       s = "    {\n        rosetta::jvm::TypeOps ops;\n";
            s += "        ops.destroy = &rosetta::jvm::destroy_inst<" + t + ">;\n";
            if (k.is_default_constructible) {
                s += "        ops.create  = &rosetta::jvm::create_default<" + t + ">;\n";
            }

            // Fields → get + (readonly / ranged / plain) set.
            for (const auto &f : k.fields) {
                if (!jsonable_type(f.type)) {
                    continue;
                }
                const std::string mp = "&" + t + "::" + f.name;
                s += "        ops.get[\"" + f.name + "\"] = &rosetta::jvm::get_field<" + mp + ">;\n";
                if (f.is_readonly) {
                    s += "        ops.set[\"" + f.name + "\"] = &rosetta::jvm::set_field_readonly<" +
                         mp + ", \"" + f.name + "\">;\n";
                } else if (f.range.has && f.type.kind == "number") {
                    s += "        ops.set[\"" + f.name + "\"] = &rosetta::jvm::set_field_ranged<" +
                         mp + ", \"" + f.name + "\", " + csx_double_lit(f.range.min) + ", " +
                         csx_double_lit(f.range.max) + ">;\n";
                } else {
                    s += "        ops.set[\"" + f.name + "\"] = &rosetta::jvm::set_field<" + mp +
                         ">;\n";
                }
            }

            // Methods → call (instance) / call_function (static; a static member
            // is a plain function pointer).
            for (const auto &m : k.methods) {
                if (!jsonable_method(m)) {
                    continue;
                }
                const std::string mp = "&" + t + "::" + m.name;
                if (m.is_static) {
                    s += "        ops.scall[\"" + m.name + "\"] = &rosetta::jvm::call_function<" + mp +
                         ">;\n";
                } else {
                    s += "        ops.call[\"" + m.name + "\"] = &rosetta::jvm::call_method<" + mp +
                         ">;\n";
                }
            }

            // Constructors → construct<T, Args...>, keyed by arity. Skip 0-arg
            // (handled by ops.create) and any whose params aren't marshalable.
            for (std::size_t i = 0; i < k.ctor_param_cpp.size(); ++i) {
                const auto &ir = k.ctors[i];
                if (ir.empty()) {
                    continue;
                }
                bool ok = true;
                for (const auto &p : ir) {
                    ok = ok && jsonable_type(p.type);
                }
                if (!ok) {
                    continue;
                }
                std::string types;
                for (const auto &spelling : k.ctor_param_cpp[i]) {
                    types += ", " + qualify_std(spelling);
                }
                s += "        ops.ctors[" + std::to_string(ir.size()) +
                     "] = &rosetta::jvm::construct<" + t + types + ">;\n";
            }

            s += "        rosetta::jvm::registry()[\"" + t + "\"] = std::move(ops);\n    }\n";
            return s;
        }

        inline std::string java_expanded_registrations(const GenContext &c) {
            std::string s;
            // Enums: literal name -> value map (reflection-free).
            for (const auto &e : c.enums) {
                s += "    rosetta::jvm::enums()[\"" + e.name + "\"] = rosetta::jvm::json{";
                for (std::size_t i = 0; i < e.values.size(); ++i) {
                    s += (i ? ", " : "") + std::string("{\"") + e.values[i].name + "\", " +
                         std::to_string(e.values[i].value) + "}";
                }
                s += "};\n";
            }
            for (const auto &k : c.classes) {
                s += jvx_class(k);
            }
            for (const auto &f : c.functions) {
                if (jsonable_function(f)) {
                    s += "    rosetta::jvm::functions()[\"" + f.name +
                         "\"] = &rosetta::jvm::call_function<&" + f.qualified + ">;\n";
                }
            }
            return s;
        }

        inline std::string java_expanded_source(const GenContext &c) {
            std::string out =
                "// Generated by rosetta::generate (expanded, reflection-free) — "
                "do not edit by hand.\n";
            out += "#include <rosetta/backends/java_runtime.h>\n";
            out += "#include <cstdlib>\n#include <cstring>\n#include <mutex>\n#include <string>\n";
            // User headers (deduped) — the only thing the shim needs besides the
            // runtime; no rosetta/annotations.h (these headers are stock C++).
            auto add = [&](const std::string &h) {
                if (h.empty()) {
                    return;
                }
                const std::string line = "#include \"" + h + "\"\n";
                if (out.find(line) == std::string::npos) {
                    out += line;
                }
            };
            for (const auto &k : c.classes) {
                add(k.header);
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            out += "\nnamespace {\n\nvoid register_all() {\n";
            out += java_expanded_registrations(c);
            out += "}\n";
            out += JVX_ABI;
            return out;
        }

        inline std::string JavaExpandedBackend::render(const GenContext &c) const {
            return java_expanded_source(c);
        }

        inline void JavaExpandedBackend::emit(const GenContext &c) const {
            const auto dir    = c.out_dir / "java-expanded";
            const auto srcdir = dir / "src" / "main" / "java" / java_pkgdir(c);

            // Native shim (reflection-free) + its stock-compiler build.
            write_file(dir / "auto_java.cpp", java_expanded_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(JVX_CMAKE, c));

            // The Java sources / pom.xml / README are identical to the thin
            // backend's — same FFM protocol, same wrappers.
            write_file(srcdir / "Native.java", java_native(c));
            write_file(srcdir / "Rt.java", java_runtime_src(c));
            for (const auto &e : c.enums) {
                write_file(srcdir / (e.name + ".java"), java_enum(c, e));
            }
            for (const auto &k : c.classes) {
                write_file(srcdir / (k.name + ".java"), java_class(c, k));
            }
            const std::string fns = java_functions(c);
            if (!fns.empty()) {
                write_file(srcdir / "Functions.java", fns);
            }

            write_file(dir / "pom.xml", subst(JAVA_POM, {{"LIB", c.lib}}));
            const std::string doc =
                subst(JAVA_README,
                      {{"LIB", c.lib}, {"PKG", java_pkg(c)}, {"PKGDIR", java_pkgdir(c)}}) +
                readme_body_of(c.classes);
            write_file(dir / "README.md", doc);
        }

    } // namespace gen_detail
} // namespace rosetta
