// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Java generation backend. Included by inline/generate.hxx, which provides the
// shared render helpers (subst / includes_of / render_meta / readme /
// write_file / readme_body_of) and the jsonable_* predicates this file relies
// on. The exact sibling of csharp_backend.hxx.
//
// Two artifacts work together:
//   - auto_java.cpp: a C++26 shim that registers each reflected type with the
//     runtime in <rosetta/visitors/java_visitor.h> and exports a flat C ABI
//     (rosetta_java_*). Built into a shared library by the generated CMake.
//   - the Java sources: idiomatic wrappers rendered from the reflected IR. Each
//     class is a handle (an integer id into the native store); property/method
//     access is a JSON round-trip through the C ABI via the Foreign Function &
//     Memory API (java.lang.foreign), with Jackson doing the (de)serialisation.
//     This part is pure-data templating — no C++ is involved.
//
// The Java surface matches the runtime's: scalars, bool, String, enums (by
// value) and List<…> of those. Members using any other type are skipped on both
// sides (jsonable_type / jsonable_method here mirror jvm::supported in the
// runtime), so the wrapper never references a C ABI operation that wasn't
// registered.

#pragma once

namespace rosetta {
    namespace gen_detail {

        // ---- the native shim (auto_java.cpp) ----

        constexpr std::string_view JAVA_CPP =
            R"CPP(// Generated by rosetta::generate — do not edit by hand.
{{INCLUDES}}#include <rosetta/visitors/java_visitor.h>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <string>

namespace {

void register_all() {
{{BINDINGS}}}

void ensure_registered() {
    static std::once_flag once;
    std::call_once(once, [] { register_all(); });
}

// Copy a std::string into a malloc'd C string; the Java side releases it via
// rosetta_java_free. Returns nullptr only on allocation failure.
char *dup_cstr(const std::string &s) {
    char *p = static_cast<char *>(std::malloc(s.size() + 1));
    if (p) {
        std::memcpy(p, s.c_str(), s.size() + 1);
    }
    return p;
}

} // namespace

extern "C" {

ROSETTA_JAVA_EXPORT int rosetta_java_create(const char *type, const char *args) {
    ensure_registered();
    return rosetta::jvm::api_create(type, args);
}

ROSETTA_JAVA_EXPORT int rosetta_java_destroy(const char *type, int id) {
    ensure_registered();
    return rosetta::jvm::api_destroy(type, id) ? 1 : 0;
}

ROSETTA_JAVA_EXPORT char *rosetta_java_get_field(const char *type, int id, const char *field) {
    ensure_registered();
    return dup_cstr(rosetta::jvm::api_get(type, id, field));
}

ROSETTA_JAVA_EXPORT char *rosetta_java_set_field(const char *type, int id, const char *field,
                                                 const char *value) {
    ensure_registered();
    return dup_cstr(rosetta::jvm::api_set(type, id, field, value));
}

ROSETTA_JAVA_EXPORT char *rosetta_java_call_method(const char *type, int id, const char *method,
                                                   const char *args) {
    ensure_registered();
    return dup_cstr(rosetta::jvm::api_call(type, id, method, args));
}

ROSETTA_JAVA_EXPORT char *rosetta_java_call_static(const char *type, const char *method,
                                                   const char *args) {
    ensure_registered();
    return dup_cstr(rosetta::jvm::api_scall(type, method, args));
}

ROSETTA_JAVA_EXPORT char *rosetta_java_call_function(const char *name, const char *args) {
    ensure_registered();
    return dup_cstr(rosetta::jvm::api_function(name, args));
}

ROSETTA_JAVA_EXPORT char *rosetta_java_enum_values(const char *type) {
    ensure_registered();
    return dup_cstr(rosetta::jvm::api_enum(type));
}

ROSETTA_JAVA_EXPORT void rosetta_java_free(char *p) { std::free(p); }

} // extern "C"
)CPP";

        // ---- the native build (identical shape to the C# backend) ----

        constexpr std::string_view JAVA_CMAKE = R"CMK({{HEADER_BLOCK}}
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

include(FetchContent)
FetchContent_Declare(json
    GIT_REPOSITORY https://github.com/nlohmann/json.git
    GIT_TAG        v3.11.3)
FetchContent_MakeAvailable(json)

# A plain shared library: the Java wrapper reaches it through the Foreign
# Function & Memory API. Only the rosetta_java_* entry points are exported
# (visibility hidden by default).
add_library({{LIB}} SHARED auto_java.cpp)
set_target_properties({{LIB}} PROPERTIES
    POSITION_INDEPENDENT_CODE ON
    CXX_VISIBILITY_PRESET hidden
    VISIBILITY_INLINES_HIDDEN ON)

target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})
{{USER_LIB_BLOCK}}
target_link_libraries({{LIB}} PRIVATE nlohmann_json::nlohmann_json)

target_compile_options({{LIB}} PRIVATE
    {{REFLECTION_FLAGS}})

target_link_options({{LIB}} PRIVATE
    {{STDLIB_LINK}})
)CMK";

        constexpr std::string_view JAVA_POM = R"POM(<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>rosetta.generated</groupId>
  <artifactId>{{LIB}}</artifactId>
  <version>0.1.0</version>
  <packaging>jar</packaging>

  <properties>
    <!-- The Foreign Function & Memory API (java.lang.foreign) is stable from
         JDK 22 (JEP 454) — no preview flag needed. -->
    <maven.compiler.release>22</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.17.1</version>
    </dependency>
  </dependencies>
</project>
)POM";

        constexpr std::string_view JAVA_README = R"MD(# `{{LIB}}` (java)

Auto-generated Java bindings. Two pieces work together:

- **`auto_java.cpp`** → a native shared library exposing a flat C ABI
  (`rosetta_java_*`). Built with the C++26 reflection toolchain.
- **the Java sources** (under `src/main/java/{{PKGDIR}}/`) → idiomatic wrappers.
  Each class is a handle into the native instance store; property and method
  access is a JSON round-trip through the C ABI via the Foreign Function & Memory
  API (`java.lang.foreign`), with Jackson doing the (de)serialisation.

## Build

```sh
# 1. the native library (produces lib{{LIB}}.{dylib,so} / {{LIB}}.dll)
cmake -S . -B build && cmake --build build

# 2. the Java jar
mvn package
```

## Run

The JVM must find the native library at run time. Point `java.library.path` at
the CMake build dir, and (JDK 22+) allow native access:

```sh
java --enable-native-access=ALL-UNNAMED \
     -Djava.library.path=build \
     -cp target/{{LIB}}-0.1.0.jar:$(mvn -q help:evaluate -Dexpression=settings.localRepository -DforceStdout)/com/fasterxml/jackson/... \
     {{PKG}}.Example
```

(Simpler: run from an IDE/Maven exec with `java.library.path=build`.)

## Use

```java
import {{PKG}}.*;

try (var p = new Person()) {          // AutoCloseable — frees the native instance
    p.setName("Alice");
    System.out.println(p.greet("Hi"));
}
```

Boundary types: scalars, `boolean`, `String`, enums (by value), and `List<…>`
of those. Members using any other type are omitted from both sides.

)MD";

        // -------- Java rendering helpers --------

        // Sanitise an arbitrary library name into a lower-case Java package
        // segment (letters / digits / underscore; must not start with a digit).
        inline std::string java_pkg_seg(const std::string &s) {
            auto lower = [](char ch) {
                return (ch >= 'A' && ch <= 'Z') ? char(ch - 'A' + 'a') : ch;
            };
            auto is_alnum = [](char ch) {
                return (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
                       (ch >= '0' && ch <= '9');
            };
            std::string out;
            for (char ch : s) {
                out += (is_alnum(ch) ? lower(ch) : '_');
            }
            if (out.empty() || (out.front() >= '0' && out.front() <= '9')) {
                out.insert(out.begin(), '_');
            }
            return out;
        }

        // The package the generated Java lives in, and its on-disk sub-path.
        inline std::string java_pkg(const GenContext &c) {
            return "rosetta.gen." + java_pkg_seg(c.lib);
        }
        inline std::string java_pkgdir(const GenContext &c) {
            return "rosetta/gen/" + java_pkg_seg(c.lib);
        }

        // The boxed (reference) Java type — used inside generics and Jackson
        // TypeReferences. Only ever called for jsonable types.
        inline std::string java_box(const GenType &t) {
            if (t.kind == "boolean") {
                return "Boolean";
            }
            if (t.kind == "string") {
                return "String";
            }
            if (t.kind == "number") {
                return t.integer ? "Long" : "Double";
            }
            if (t.kind == "enum") {
                return t.object.empty() ? "Long" : t.object;
            }
            if (t.kind == "vector") {
                return "java.util.List<" +
                       (t.element.empty() ? std::string("Object") : java_box(t.element.front())) +
                       ">";
            }
            return "Object";
        }

        // The Java type used in a method / field signature (unboxed scalars).
        inline std::string java_sig(const GenType &t) {
            if (t.kind == "boolean") {
                return "boolean";
            }
            if (t.kind == "number") {
                return t.integer ? "long" : "double";
            }
            return java_box(t); // String / enum / List<…> are already reference types
        }

        // A Jackson TypeReference literal capturing the (boxed) target type.
        inline std::string java_typeref(const GenType &t) {
            return "new TypeReference<" + java_box(t) + ">(){}";
        }

        // "double arg0, double arg1"
        inline std::string java_param_sig(const std::vector<GenParam> &ps) {
            std::string s;
            for (std::size_t i = 0; i < ps.size(); ++i) {
                s += (i ? ", " : "") + java_sig(ps[i].type) + " " + ps[i].name;
            }
            return s;
        }

        // "arg0, arg1" — the varargs forwarded to the Rt helpers.
        inline std::string java_arg_names(const std::vector<GenParam> &ps) {
            std::string s;
            for (std::size_t i = 0; i < ps.size(); ++i) {
                s += (i ? ", " : "") + ps[i].name;
            }
            return s;
        }

        inline bool java_ctor_jsonable(const std::vector<GenParam> &ps) {
            for (const auto &p : ps) {
                if (!jsonable_type(p.type)) {
                    return false;
                }
            }
            return true;
        }

        // Capitalise the first letter for a get/set accessor name.
        inline std::string java_cap(const std::string &s) {
            std::string out = s;
            if (!out.empty() && out.front() >= 'a' && out.front() <= 'z') {
                out.front() = char(out.front() - 'a' + 'A');
            }
            return out;
        }

        // ---- Native.java : the FFM downcall handles ----

        inline std::string java_native(const GenContext &c) {
            std::string s = "// Generated by rosetta::generate — do not edit by hand.\n";
            s += "package " + java_pkg(c) + ";\n\n";
            s += "import java.lang.foreign.AddressLayout;\n";
            s += "import java.lang.foreign.FunctionDescriptor;\n";
            s += "import java.lang.foreign.Linker;\n";
            s += "import java.lang.foreign.MemorySegment;\n";
            s += "import java.lang.foreign.SymbolLookup;\n";
            s += "import java.lang.foreign.ValueLayout;\n";
            s += "import java.lang.invoke.MethodHandle;\n\n";
            s += "/** Foreign Function & Memory downcall handles for the rosetta_java_* C ABI. */\n";
            s += "final class Native {\n";
            s += "    private Native() {}\n\n";
            s += "    static {\n";
            s += "        System.loadLibrary(\"" + c.lib + "\");\n";
            s += "    }\n\n";
            s += "    private static final Linker LINKER = Linker.nativeLinker();\n";
            s += "    private static final SymbolLookup LOOKUP = SymbolLookup.loaderLookup();\n\n";
            s += "    private static final ValueLayout.OfInt I = ValueLayout.JAVA_INT;\n";
            s += "    private static final AddressLayout A = ValueLayout.ADDRESS;\n\n";
            s += "    private static MethodHandle h(String name, FunctionDescriptor fd) {\n";
            s += "        return LINKER.downcallHandle(\n";
            s += "            LOOKUP.find(name).orElseThrow(\n";
            s += "                () -> new UnsatisfiedLinkError(\"missing symbol: \" + name)),\n";
            s += "            fd);\n";
            s += "    }\n\n";
            s += "    static final MethodHandle CREATE =\n";
            s += "        h(\"rosetta_java_create\", FunctionDescriptor.of(I, A, A));\n";
            s += "    static final MethodHandle DESTROY =\n";
            s += "        h(\"rosetta_java_destroy\", FunctionDescriptor.of(I, A, I));\n";
            s += "    static final MethodHandle GET_FIELD =\n";
            s += "        h(\"rosetta_java_get_field\", FunctionDescriptor.of(A, A, I, A));\n";
            s += "    static final MethodHandle SET_FIELD =\n";
            s += "        h(\"rosetta_java_set_field\", FunctionDescriptor.of(A, A, I, A, A));\n";
            s += "    static final MethodHandle CALL_METHOD =\n";
            s += "        h(\"rosetta_java_call_method\", FunctionDescriptor.of(A, A, I, A, A));\n";
            s += "    static final MethodHandle CALL_STATIC =\n";
            s += "        h(\"rosetta_java_call_static\", FunctionDescriptor.of(A, A, A, A));\n";
            s += "    static final MethodHandle CALL_FUNCTION =\n";
            s += "        h(\"rosetta_java_call_function\", FunctionDescriptor.of(A, A, A));\n";
            s += "    static final MethodHandle ENUM_VALUES =\n";
            s += "        h(\"rosetta_java_enum_values\", FunctionDescriptor.of(A, A));\n";
            s += "    static final MethodHandle FREE =\n";
            s += "        h(\"rosetta_java_free\", FunctionDescriptor.ofVoid(A));\n";
            s += "}\n";
            return s;
        }

        // ---- Rt.java : JSON marshalling + envelope handling ----
        //
        // All native invocation lives here so the per-class wrappers stay free of
        // Arena / MethodHandle / Throwable plumbing.
        inline std::string java_runtime_src(const GenContext &c) {
            std::string s = "// Generated by rosetta::generate — do not edit by hand.\n";
            s += "package " + java_pkg(c) + ";\n\n";
            s += "import com.fasterxml.jackson.core.type.TypeReference;\n";
            s += "import com.fasterxml.jackson.databind.JsonNode;\n";
            s += "import com.fasterxml.jackson.databind.ObjectMapper;\n";
            s += "import java.lang.foreign.Arena;\n";
            s += "import java.lang.foreign.MemorySegment;\n\n";
            s += R"JAVA(/** Thrown when the native side reports an error envelope. */
class RosettaException extends RuntimeException {
    RosettaException(String message) { super(message); }
}

/** Marshalling helpers shared by every generated wrapper. */
final class Rt {
    private Rt() {}

    static final ObjectMapper MAPPER = new ObjectMapper();

    static String ser(Object v) {
        try {
            return MAPPER.writeValueAsString(v);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    // Read a native char* result, free it, and return its text.
    private static String take(MemorySegment p) {
        if (p == null || p.address() == 0) {
            return "";
        }
        String s = p.reinterpret(Long.MAX_VALUE).getString(0);
        try {
            Native.FREE.invoke(p);
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }
        return s;
    }

    // Parse the {"ok":…,"value":…,"error":…} envelope, throwing on failure.
    private static JsonNode unwrap(MemorySegment p) {
        try {
            JsonNode root = MAPPER.readTree(take(p));
            if (!root.path("ok").asBoolean()) {
                throw new RosettaException(root.path("error").asText("error"));
            }
            return root.path("value");
        } catch (RosettaException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private static <T> T conv(MemorySegment p, TypeReference<T> ref) {
        return MAPPER.convertValue(unwrap(p), ref);
    }

    static int newInstance(String type, Object... args) {
        try (Arena a = Arena.ofConfined()) {
            int id = (int) Native.CREATE.invoke(a.allocateFrom(type), a.allocateFrom(ser(args)));
            if (id < 0) {
                throw new RosettaException("failed to construct " + type);
            }
            return id;
        } catch (RosettaException e) {
            throw e;
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }
    }

    static void destroy(String type, int id) {
        try (Arena a = Arena.ofConfined()) {
            Native.DESTROY.invoke(a.allocateFrom(type), id);
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }
    }

    static <T> T getField(String type, int id, String field, TypeReference<T> ref) {
        try (Arena a = Arena.ofConfined()) {
            MemorySegment r = (MemorySegment) Native.GET_FIELD.invoke(
                a.allocateFrom(type), id, a.allocateFrom(field));
            return conv(r, ref);
        } catch (RosettaException e) {
            throw e;
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }
    }

    static void setField(String type, int id, String field, Object value) {
        try (Arena a = Arena.ofConfined()) {
            MemorySegment r = (MemorySegment) Native.SET_FIELD.invoke(
                a.allocateFrom(type), id, a.allocateFrom(field), a.allocateFrom(ser(value)));
            unwrap(r);
        } catch (RosettaException e) {
            throw e;
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }
    }

    static <T> T callMethod(String type, int id, String method, TypeReference<T> ref, Object... args) {
        try (Arena a = Arena.ofConfined()) {
            MemorySegment r = (MemorySegment) Native.CALL_METHOD.invoke(
                a.allocateFrom(type), id, a.allocateFrom(method), a.allocateFrom(ser(args)));
            return conv(r, ref);
        } catch (RosettaException e) {
            throw e;
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }
    }

    static void callMethodVoid(String type, int id, String method, Object... args) {
        try (Arena a = Arena.ofConfined()) {
            MemorySegment r = (MemorySegment) Native.CALL_METHOD.invoke(
                a.allocateFrom(type), id, a.allocateFrom(method), a.allocateFrom(ser(args)));
            unwrap(r);
        } catch (RosettaException e) {
            throw e;
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }
    }

    static <T> T callStatic(String type, String method, TypeReference<T> ref, Object... args) {
        try (Arena a = Arena.ofConfined()) {
            MemorySegment r = (MemorySegment) Native.CALL_STATIC.invoke(
                a.allocateFrom(type), a.allocateFrom(method), a.allocateFrom(ser(args)));
            return conv(r, ref);
        } catch (RosettaException e) {
            throw e;
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }
    }

    static void callStaticVoid(String type, String method, Object... args) {
        try (Arena a = Arena.ofConfined()) {
            MemorySegment r = (MemorySegment) Native.CALL_STATIC.invoke(
                a.allocateFrom(type), a.allocateFrom(method), a.allocateFrom(ser(args)));
            unwrap(r);
        } catch (RosettaException e) {
            throw e;
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }
    }

    static <T> T callFunction(String name, TypeReference<T> ref, Object... args) {
        try (Arena a = Arena.ofConfined()) {
            MemorySegment r = (MemorySegment) Native.CALL_FUNCTION.invoke(
                a.allocateFrom(name), a.allocateFrom(ser(args)));
            return conv(r, ref);
        } catch (RosettaException e) {
            throw e;
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }
    }

    static void callFunctionVoid(String name, Object... args) {
        try (Arena a = Arena.ofConfined()) {
            MemorySegment r = (MemorySegment) Native.CALL_FUNCTION.invoke(
                a.allocateFrom(name), a.allocateFrom(ser(args)));
            unwrap(r);
        } catch (RosettaException e) {
            throw e;
        } catch (Throwable t) {
            throw new RuntimeException(t);
        }
    }
}
)JAVA";
            return s;
        }

        // ---- one handle-backed wrapper class per type ----

        inline std::string java_class(const GenContext &c, const GenClass &k) {
            std::string s = "// Generated by rosetta::generate — do not edit by hand.\n";
            s += "package " + java_pkg(c) + ";\n\n";
            s += "import com.fasterxml.jackson.core.type.TypeReference;\n\n";
            if (!k.doc.empty()) {
                s += "/** " + k.name + " */\n";
            }
            s += "public final class " + k.name + " implements AutoCloseable {\n";
            s += "    private static final String _t = \"" + k.name + "\";\n";
            s += "    private int _id;\n\n";

            // Constructors, deduped by erased Java signature.
            std::vector<std::string> seen_sigs;
            auto emit_ctor = [&](const std::vector<GenParam> &ps) {
                const std::string sig = java_param_sig(ps);
                for (const auto &s2 : seen_sigs) {
                    if (s2 == sig) {
                        return;
                    }
                }
                seen_sigs.push_back(sig);
                const std::string names = java_arg_names(ps);
                s += "    public " + k.name + "(" + sig + ") {\n";
                s += "        _id = Rt.newInstance(_t" + (names.empty() ? "" : ", " + names) +
                     ");\n";
                s += "    }\n\n";
            };
            if (k.is_default_constructible) {
                emit_ctor({});
            }
            for (const auto &ct : k.ctors) {
                if (!ct.empty() && java_ctor_jsonable(ct)) {
                    emit_ctor(ct);
                }
            }
            if (seen_sigs.empty()) {
                // No JSON-marshalable constructor — block construction so a broken
                // (id 0) instance can't be made.
                s += "    private " + k.name + "() { } // no JSON-marshalable constructor\n\n";
            }

            s += "    @Override\n";
            s += "    public void close() {\n";
            s += "        if (_id > 0) { Rt.destroy(_t, _id); _id = 0; }\n";
            s += "    }\n";

            // Fields → get/set accessors.
            for (const auto &f : k.fields) {
                if (!jsonable_type(f.type)) {
                    continue;
                }
                const std::string ty  = java_sig(f.type);
                const std::string cap = java_cap(f.name);
                if (!f.doc.empty()) {
                    s += "\n    /** " + f.doc + " */";
                }
                s += "\n    public " + ty + " get" + cap + "() {\n";
                s += "        return Rt.getField(_t, _id, \"" + f.name + "\", " +
                     java_typeref(f.type) + ");\n";
                s += "    }\n";
                if (!f.is_readonly) {
                    s += "    public void set" + cap + "(" + ty + " value) {\n";
                    s += "        Rt.setField(_t, _id, \"" + f.name + "\", value);\n";
                    s += "    }\n";
                }
            }

            // Methods.
            for (const auto &m : k.methods) {
                if (!jsonable_method(m)) {
                    continue;
                }
                const std::string sig   = java_param_sig(m.params);
                const std::string names = java_arg_names(m.params);
                const std::string tail  = names.empty() ? "" : ", " + names;
                if (!m.doc.empty()) {
                    s += "\n    /** " + m.doc + " */";
                }
                s += "\n    public " + std::string(m.is_static ? "static " : "");
                if (m.ret.kind == "void") {
                    s += "void " + m.name + "(" + sig + ") {\n";
                    s += m.is_static
                             ? "        Rt.callStaticVoid(_t, \"" + m.name + "\"" + tail + ");\n"
                             : "        Rt.callMethodVoid(_t, _id, \"" + m.name + "\"" + tail +
                                   ");\n";
                } else {
                    const std::string ret = java_sig(m.ret);
                    s += ret + " " + m.name + "(" + sig + ") {\n";
                    s += m.is_static
                             ? "        return Rt.callStatic(_t, \"" + m.name + "\", " +
                                   java_typeref(m.ret) + tail + ");\n"
                             : "        return Rt.callMethod(_t, _id, \"" + m.name + "\", " +
                                   java_typeref(m.ret) + tail + ");\n";
                }
                s += "    }\n";
            }

            s += "}\n";
            return s;
        }

        // ---- one Java enum per enumeration (int-valued, Jackson-friendly) ----

        inline std::string java_enum(const GenContext &c, const GenEnum &e) {
            std::string s = "// Generated by rosetta::generate — do not edit by hand.\n";
            s += "package " + java_pkg(c) + ";\n\n";
            s += "import com.fasterxml.jackson.annotation.JsonCreator;\n";
            s += "import com.fasterxml.jackson.annotation.JsonValue;\n\n";
            if (!e.doc.empty()) {
                s += "/** " + e.name + " */\n";
            }
            s += "public enum " + e.name + " {\n";
            for (std::size_t i = 0; i < e.values.size(); ++i) {
                s += "    " + e.values[i].name + "(" + std::to_string(e.values[i].value) + ")" +
                     (i + 1 < e.values.size() ? "," : ";") + "\n";
            }
            if (e.values.empty()) {
                s += "    ;\n";
            }
            s += "\n    private final long value;\n";
            s += "    " + e.name + "(long v) { this.value = v; }\n\n";
            s += "    @JsonValue\n";
            s += "    public long value() { return value; }\n\n";
            s += "    @JsonCreator\n";
            s += "    public static " + e.name + " of(long v) {\n";
            s += "        for (" + e.name + " c : values()) {\n";
            s += "            if (c.value == v) { return c; }\n";
            s += "        }\n";
            s += "        throw new IllegalArgumentException(\"invalid " + e.name + ": \" + v);\n";
            s += "    }\n";
            s += "}\n";
            return s;
        }

        // ---- free functions → a static facade ----

        inline std::string java_functions(const GenContext &c) {
            bool any = false;
            for (const auto &f : c.functions) {
                if (jsonable_function(f)) {
                    any = true;
                    break;
                }
            }
            if (!any) {
                return {};
            }
            std::string s = "// Generated by rosetta::generate — do not edit by hand.\n";
            s += "package " + java_pkg(c) + ";\n\n";
            s += "import com.fasterxml.jackson.core.type.TypeReference;\n\n";
            s += "public final class Functions {\n";
            s += "    private Functions() {}\n";
            for (const auto &f : c.functions) {
                if (!jsonable_function(f)) {
                    continue;
                }
                const std::string sig   = java_param_sig(f.params);
                const std::string names = java_arg_names(f.params);
                const std::string tail  = names.empty() ? "" : ", " + names;
                if (!f.doc.empty()) {
                    s += "\n    /** " + f.doc + " */";
                }
                s += "\n    public static ";
                if (f.ret.kind == "void") {
                    s += "void " + f.name + "(" + sig + ") {\n";
                    s += "        Rt.callFunctionVoid(\"" + f.name + "\"" + tail + ");\n";
                } else {
                    s += java_sig(f.ret) + " " + f.name + "(" + sig + ") {\n";
                    s += "        return Rt.callFunction(\"" + f.name + "\", " + java_typeref(f.ret) +
                         tail + ");\n";
                }
                s += "    }\n";
            }
            s += "}\n";
            return s;
        }

        // ---- the register_all() body: one bind_java* call per exposed entity ----

        inline std::string java_registrations(const GenContext &c) {
            std::string s;
            for (const auto &e : c.enums) {
                s += "    rosetta::bind_java_enum<" + e.name + ">(\"" + e.name + "\");\n";
            }
            for (const auto &k : c.classes) {
                s += "    rosetta::bind_java<" + k.name + ">(\"" + k.name + "\");\n";
            }
            for (const auto &f : c.functions) {
                s += "    rosetta::bind_java_function<^^" + f.qualified + ">(\"" + f.name + "\");\n";
            }
            return s;
        }

        inline std::string java_source(const GenContext &c) {
            // includes_of() also emits the `using namespace` a namespaced user
            // library needs (so unqualified bind_java<T> resolves).
            return subst(JAVA_CPP, {{"INCLUDES", includes_of(c)},
                                    {"BINDINGS", java_registrations(c)}});
        }

        inline std::string JavaBackend::render(const GenContext &c) const {
            return java_source(c);
        }

        inline void JavaBackend::emit(const GenContext &c) const {
            const auto dir    = c.out_dir / "java";
            const auto srcdir = dir / "src" / "main" / "java" / java_pkgdir(c);

            // Native shim + its build.
            write_file(dir / "auto_java.cpp", java_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(JAVA_CMAKE, c));

            // Java sources.
            write_file(srcdir / "Native.java", java_native(c));
            write_file(srcdir / "Rt.java", java_runtime_src(c));
            for (const auto &e : c.enums) {
                write_file(srcdir / (e.name + ".java"), java_enum(c, e));
            }
            for (const auto &k : c.classes) {
                write_file(srcdir / (k.name + ".java"), java_class(c, k));
            }
            const std::string fns = java_functions(c);
            if (!fns.empty()) {
                write_file(srcdir / "Functions.java", fns);
            }

            // Maven project + docs.
            write_file(dir / "pom.xml", subst(JAVA_POM, {{"LIB", c.lib}}));
            const std::string doc =
                subst(JAVA_README,
                      {{"LIB", c.lib}, {"PKG", java_pkg(c)}, {"PKGDIR", java_pkgdir(c)}}) +
                readme_body_of(c.classes);
            write_file(dir / "README.md", doc);
        }

    } // namespace gen_detail
} // namespace rosetta
