// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// JSON serialization backend. Unlike the other "pure-data" backends, this one
// emits no per-type code: serialization is done at runtime by the reflection
// visitor in <rosetta/visitors/json_visitor.h> (rosetta::to_json /
// rosetta::from_json). The backend therefore only scaffolds a runnable demo
// (plus CMake + README) — the single visitor header serializes every class.
// Included by inline/generate.hxx.

#pragma once

namespace rosetta {
    namespace gen_detail {

        constexpr std::string_view JSON_CMAKE = R"CMK({{HEADER_BLOCK}}
project({{LIB}}_json CXX)

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

include(FetchContent)
FetchContent_Declare(json
    GIT_REPOSITORY https://github.com/nlohmann/json.git
    GIT_TAG        v3.11.3)
FetchContent_MakeAvailable(json)

add_executable({{LIB}}_demo demo.cpp)

target_include_directories({{LIB}}_demo PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

target_link_libraries({{LIB}}_demo PRIVATE nlohmann_json::nlohmann_json)

# Serialization is reflection-driven, so the demo needs the reflection flags.
target_compile_options({{LIB}}_demo PRIVATE
    -freflection -freflection-latest -fexperimental-library -fannotation-attributes)

target_link_options({{LIB}}_demo PRIVATE
    -nostdlib++ -L${ROSETTA_STDLIB} -Wl,-rpath,${ROSETTA_STDLIB}
    -lc++ -lc++abi)
)CMK";

        // A runnable demo: serialize a default instance of each class with the
        // reflection serializer, then value-round-trip the first one that has
        // public fields.
        inline std::string json_demo(const GenContext &c) {
            std::string d = "// Generated by rosetta::generate — do not edit by hand.\n";
            d += "#include <rosetta/visitors/json_visitor.h>\n";
            d += includes_of(c); // rosetta/annotations.h + user/enum headers
            d += "#include <iostream>\n\n";
            d += "int main() {\n";
            d += "    std::cout << \"-- serialize default instances --\\n\";\n";
            for (const auto &k : c.classes) {
                d += "    std::cout << \"" + k.name + ": \" << rosetta::to_json(" + k.name +
                     "{}).dump() << \"\\n\";\n";
            }

            const GenClass *rt = nullptr;
            for (const auto &k : c.classes) {
                if (!k.fields.empty()) {
                    rt = &k;
                    break;
                }
            }
            if (rt) {
                d += "\n    std::cout << \"\\n-- round-trip " + rt->name + " --\\n\";\n";
                d += "    " + rt->name + " a{};\n";
                int n = 0;
                for (const auto &f : rt->fields) {
                    if (f.type.kind == "number") {
                        d += "    a." + f.name + " = " + std::to_string(++n) + ";\n";
                    }
                }
                d += "    nlohmann::json j = rosetta::to_json(a);\n";
                d += "    std::cout << \"to_json:   \" << j.dump() << \"\\n\";\n";
                d += "    " + rt->name + " b = rosetta::from_json<" + rt->name + ">(j);\n";
                d += "    std::cout << \"from_json: \" << rosetta::to_json(b).dump() << \"\\n\";\n";
            }
            d += "    return 0;\n}\n";
            return d;
        }

        inline void JsonBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "json";
            write_file(dir / "demo.cpp", json_demo(c));
            write_file(dir / "CMakeLists.txt", render_meta(JSON_CMAKE, c));
            write_file(dir / "README.md", readme("json", c));
        }

    } // namespace gen_detail
} // namespace rosetta
