// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Expanded (reflection-free) nanobind backend. Included by inline/generate.hxx
// after nanobind_backend.h and python_expanded_backend.h (whose qualify_std()
// it reuses), plus the shared render helpers (subst / num_str / render_meta /
// write_file).

#pragma once

namespace rosetta {
    namespace gen_detail {

        // A stock-toolchain CMake: C++17, the pip `nanobind` package, the user's
        // include dir only. No clang-p2996, no -freflection, no -nostdlib++.
        constexpr std::string_view NANOBINDX_CMAKE =
            R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# Plain nanobind: NO C++26, NO reflection, NO rosetta headers.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

execute_process(
    COMMAND python3 -c "import sys; print(sys.executable)"
    OUTPUT_VARIABLE Python_EXECUTABLE
    OUTPUT_STRIP_TRAILING_WHITESPACE)
set(Python_EXECUTABLE "${Python_EXECUTABLE}" CACHE FILEPATH "" FORCE)

find_package(Python 3.8 COMPONENTS Interpreter Development.Module REQUIRED)

if(NOT nanobind_DIR)
    execute_process(
        COMMAND ${Python_EXECUTABLE} -c "import nanobind; print(nanobind.cmake_dir())"
        OUTPUT_VARIABLE nanobind_DIR
        OUTPUT_STRIP_TRAILING_WHITESPACE)
endif()
find_package(nanobind CONFIG REQUIRED)

nanobind_add_module({{LIB}} NB_STATIC auto_nanobind.cpp)

# Only the user's headers — rosetta's include dir is deliberately absent.
target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}})

add_custom_command(TARGET {{LIB}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        $<TARGET_FILE:{{LIB}}>
        ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
)CMK";

        // Trailing `, "doc"` for a nanobind call, or empty when there is no doc.
        // (py_lit / qualify_std come from python_expanded_backend.hxx.)
        inline std::string nbx_doc_arg(const std::string &doc) {
            return doc.empty() ? std::string{} : ", \"" + py_lit(doc) + "\"";
        }

        // One enum: nb::enum_<E>(m,"E").value("A", E::A)...;
        inline std::string nbx_enum(const GenEnum &e) {
            std::string s = "    nb::enum_<" + e.name + ">(m, \"" + e.name + "\")";
            for (const auto &v : e.values) {
                s += "\n        .value(\"" + v.name + "\", " + e.name + "::" + v.name + ")";
            }
            s += ";\n";
            return s;
        }

        // One field as a chain segment (leading '.', no newline). Mirrors
        // NanobindVisitor::field: readonly -> def_ro; arithmetic + range ->
        // validating def_prop_rw; otherwise def_rw. Member pointers keep the
        // field type implicit, so only the range setter spells a (numeric) type.
        inline std::string nbx_field_segment(const GenClass &k, const GenField &f) {
            const std::string self = k.name;
            const std::string mp   = "&" + self + "::" + f.name;
            const std::string dq   = nbx_doc_arg(f.doc);
            if (f.is_readonly) {
                return ".def_ro(\"" + f.name + "\", " + mp + dq + ")";
            }
            if (f.range.has && f.type.kind == "number") {
                const std::string ty = f.type.spelling; // arithmetic -> compilable spelling
                const std::string lo = num_str(f.range.min);
                const std::string hi = num_str(f.range.max);
                std::string       s;
                s += ".def_prop_rw(\"" + f.name + "\",\n";
                s += "            [](const " + self + " &s) { return s." + f.name + "; },\n";
                s += "            [](" + self + " &s, " + ty + " v) {\n";
                s += "                if (v < " + lo + " || v > " + hi + ")\n";
                s += "                    throw nb::value_error(\"" + f.name + " out of range [" +
                     lo + ", " + hi + "]\");\n";
                s += "                s." + f.name + " = v;\n";
                s += "            }" + dq + ")";
                return s;
            }
            return ".def_rw(\"" + f.name + "\", " + mp + dq + ")";
        }

        // One method as a chain segment. Overloads are already deduped by name in
        // the walk, so &T::m is unambiguous.
        inline std::string nbx_method_segment(const GenClass &k, const GenMethod &m) {
            const std::string mp = "&" + k.name + "::" + m.name;
            const std::string dq = nbx_doc_arg(m.doc);
            if (m.is_static) {
                return ".def_static(\"" + m.name + "\", " + mp + dq + ")";
            }
            return ".def(\"" + m.name + "\", " + mp + dq + ")";
        }

        inline std::string nbx_class(const GenClass &k) {
            std::vector<std::string> segs;

            bool saw_default = false;
            for (const auto &params : k.ctor_param_cpp) {
                if (params.empty()) {
                    saw_default = true;
                }
                std::string args;
                for (std::size_t j = 0; j < params.size(); ++j) {
                    args += (j ? ", " : "") + qualify_std(params[j]);
                }
                segs.push_back(".def(nb::init<" + args + ">())");
            }
            if (!saw_default && k.is_default_constructible) {
                segs.push_back(".def(nb::init<>())");
            }
            for (const auto &f : k.fields) {
                segs.push_back(nbx_field_segment(k, f));
            }
            for (const auto &m : k.methods) {
                segs.push_back(nbx_method_segment(k, m));
            }

            std::string s = "    nb::class_<" + k.name + ">(m, \"" + k.name + "\")";
            for (const auto &seg : segs) {
                s += "\n        " + seg;
            }
            s += ";\n";
            return s;
        }

        inline std::string nanobind_expanded_source(const GenContext &c) {
            std::string body;
            for (const auto &e : c.enums) {
                body += nbx_enum(e);
            }
            for (const auto &k : c.classes) {
                body += nbx_class(k);
            }
            for (const auto &f : c.functions) {
                body += "    m.def(\"" + f.name + "\", &" + f.qualified + nbx_doc_arg(f.doc) + ");\n";
            }

            std::string out = "// Generated by rosetta::generate (expanded, reflection-free) — "
                              "do not edit by hand.\n";
            out += "#include <nanobind/nanobind.h>\n";
            out += "#include <nanobind/stl/string.h>\n";
            out += "#include <nanobind/stl/vector.h>\n";
            out += "#include <nanobind/stl/function.h>\n";
            auto add = [&](const std::string &h) {
                if (h.empty()) {
                    return;
                }
                const std::string line = "#include \"" + h + "\"\n";
                if (out.find(line) == std::string::npos) {
                    out += line;
                }
            };
            for (const auto &k : c.classes) {
                add(k.header);
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            out += "\nnamespace nb = nanobind;\n";
            out += "\nNB_MODULE(" + c.lib + ", m) {\n";
            out += "    m.doc() = \"Auto-generated (expanded) nanobind bindings for " + c.lib +
                   ".\";\n";
            out += body;
            out += "}\n";
            return out;
        }

        inline std::string NanobindExpandedBackend::render(const GenContext &c) const {
            return nanobind_expanded_source(c);
        }

        inline void NanobindExpandedBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "nanobind-expanded";
            write_file(dir / "auto_nanobind.cpp", nanobind_expanded_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(NANOBINDX_CMAKE, c));
            write_file(dir / "README.md", readme("nanobind-expanded", c));
        }

    } // namespace gen_detail
} // namespace rosetta
