// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Expanded (reflection-free) N-API backend. Included by inline/generate.hxx
// after node_backend.h (reuses node_trampolines_of / node_virtual_methods) and
// python_expanded_backend.h (reuses qualify_std), plus the shared render
// helpers (subst / num_str / render_meta / write_file).

#pragma once

namespace rosetta {
    namespace gen_detail {

        // Stock-toolchain CMake: C++20 (member-pointer + class-type NTTPs), the
        // user's headers, and rosetta's include dir for the reflection-free
        // node_runtime.h. No clang-p2996, no -freflection, no -nostdlib++.
        constexpr std::string_view NODEX_CMAKE = R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# Plain N-API: NO C++26, NO reflection. rosetta's include dir is on the path
# only for the header-only, reflection-free node_runtime.h.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

if(NOT NODE_ADDON_API_DIR)
    execute_process(
        COMMAND node -p "require('node-addon-api').include"
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE NODE_ADDON_API_DIR
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    string(REGEX REPLACE "^\"|\"$" "" NODE_ADDON_API_DIR "${NODE_ADDON_API_DIR}")
endif()

add_library({{LIB}} SHARED auto_napi.cpp ${CMAKE_JS_SRC})
set_target_properties({{LIB}} PROPERTIES PREFIX "" SUFFIX ".node")

target_include_directories({{LIB}} PRIVATE
    ${CMAKE_JS_INC}
    ${NODE_ADDON_API_DIR}
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

target_link_libraries({{LIB}} PRIVATE ${CMAKE_JS_LIB})
target_compile_definitions({{LIB}} PRIVATE NAPI_VERSION=8)

{{USER_LIB_BLOCK}}

if(APPLE)
    target_link_options({{LIB}} PRIVATE -Wl,-undefined,dynamic_lookup)
endif()

add_custom_command(TARGET {{LIB}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        $<TARGET_FILE:{{LIB}}>
        ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
)CMK";

        // Can N-API marshal this IR type? Same surface as the reflective
        // napi_supported(): scalars, bool, string, enums, user objects, and
        // vectors of those; std::function / "unknown" cannot.
        inline bool nx_marshalable(const GenType &t) {
            if (t.kind == "unknown") {
                return false;
            }
            if (t.kind == "vector") {
                return t.element.empty() || nx_marshalable(t.element.front());
            }
            return true;
        }

        // A range bound rendered as a `double` literal. set_field_ranged's Lo/Hi
        // are `double` non-type template params, and clang rejects an `int`
        // literal (e.g. 0) there in an explicit argument list — it must read as
        // a double (0.0), so we always force a decimal point.
        inline std::string nx_double_lit(double d) {
            std::string s = num_str(d);
            if (s.find('.') == std::string::npos && s.find('e') == std::string::npos &&
                s.find('E') == std::string::npos) {
                s += ".0";
            }
            return s;
        }

        inline bool nx_method_ok(const GenMethod &m) {
            if (m.ret.kind != "void" && !nx_marshalable(m.ret)) {
                return false;
            }
            for (const auto &p : m.params) {
                if (!nx_marshalable(p.type)) {
                    return false;
                }
            }
            return true;
        }

        // One class, expanded into a DefineClass block. `held` is the concrete
        // wrapped type — the trampoline subclass when the class has virtuals,
        // else T itself — matching what bind_napi<T, Tramp> instantiates.
        inline std::string node_expanded_class(const GenClass &k) {
            const auto        virts = node_virtual_methods(k);
            const std::string held =
                virts.empty() ? k.name : "rosetta_node::Js_" + k.name;
            const std::string self = k.name;
            const std::string th   = "rosetta::Wrap<" + self + ", " + held + ">";

            std::string s = "    {\n";
            s += "        using This = " + th + ";\n";
            s += "        std::vector<Napi::ClassPropertyDescriptor<This>> props;\n";

            // Fields → InstanceAccessor(getter, setter).
            for (const auto &f : k.fields) {
                if (!nx_marshalable(f.type)) {
                    continue;
                }
                const std::string mp  = "&" + self + "::" + f.name;
                const std::string get = "&This::get_field<" + mp + ">";
                std::string       set;
                if (f.is_readonly) {
                    set = "&This::set_field_readonly<" + mp + ", \"" + f.name + "\">";
                } else if (f.range.has && f.type.kind == "number") {
                    set = "&This::set_field_ranged<" + mp + ", \"" + f.name + "\", " +
                          nx_double_lit(f.range.min) + ", " + nx_double_lit(f.range.max) + ">";
                } else {
                    set = "&This::set_field<" + mp + ">";
                }
                s += "        props.push_back(This::InstanceAccessor<" + get + ", " + set +
                     ">(\"" + f.name + "\"));\n";
            }

            // Methods → InstanceMethod / StaticMethod.
            for (const auto &m : k.methods) {
                if (!nx_method_ok(m)) {
                    continue;
                }
                const std::string mp = "&" + self + "::" + m.name;
                if (m.is_static) {
                    s += "        props.push_back(This::StaticMethod<&This::call_static<" + mp +
                         ">>(\"" + m.name + "\"));\n";
                } else {
                    s += "        props.push_back(This::InstanceMethod<&This::call_method<" + mp +
                         ">>(\"" + m.name + "\"));\n";
                }
            }

            s += "        Napi::Function ctor = This::DefineClass(env, \"" + self + "\", props);\n";
            s += "        rosetta::ctor_ref<" + self + ">() = Napi::Persistent(ctor);\n";
            s += "        rosetta::ctor_ref<" + self + ">().SuppressDestruct();\n";

            // Constructors → ctor_table entries on the held type, keyed by arity.
            for (std::size_t i = 0; i < k.ctor_param_cpp.size(); ++i) {
                const auto &ir = k.ctors[i];
                bool        ok = true;
                for (const auto &p : ir) {
                    ok = ok && nx_marshalable(p.type);
                }
                if (!ok) {
                    continue;
                }
                const auto &params = k.ctor_param_cpp[i];
                if (params.empty()) {
                    continue; // 0-arg: Wrap default-constructs `inner`, no entry needed
                }
                std::string args;
                for (std::size_t j = 0; j < params.size(); ++j) {
                    args += (j ? ", " : "") + std::string("rosetta::from_napi<std::remove_cvref_t<") +
                            qualify_std(params[j]) + ">>(info[" + std::to_string(j) + "])";
                }
                s += "        rosetta::ctor_table<" + held + ">()[" + std::to_string(params.size()) +
                     "] =\n            [](const Napi::CallbackInfo &info) { return " + held + "(" +
                     args + "); };\n";
            }

            // Override guard: record each virtual method's bound prototype fn so
            // the trampoline can tell a JS override from the inherited binding.
            if (!virts.empty()) {
                s += "        {\n";
                s += "            Napi::Object proto = ctor.Get(\"prototype\").As<Napi::Object>();\n";
                s += "            auto &guard = rosetta::napi_override_guard<" + self + ">();\n";
                for (const GenMethod *m : virts) {
                    if (!nx_method_ok(*m)) {
                        continue;
                    }
                    s += "            if (proto.Get(\"" + m->name + "\").IsFunction()) {\n";
                    s += "                guard[\"" + m->name +
                         "\"] = Napi::Persistent(proto.Get(\"" + m->name +
                         "\").As<Napi::Function>());\n";
                    s += "                guard[\"" + m->name + "\"].SuppressDestruct();\n";
                    s += "            }\n";
                }
                s += "        }\n";
            }

            s += "        exports.Set(\"" + self + "\", ctor);\n";
            s += "    }\n";
            return s;
        }

        inline std::string node_expanded_source(const GenContext &c) {
            std::string body;
            for (const auto &e : c.enums) {
                body += "    exports.Set(\"" + e.name + "\", rosetta::make_enum(env, {";
                for (std::size_t i = 0; i < e.values.size(); ++i) {
                    body += (i ? ", " : "") + std::string("{\"") + e.values[i].name + "\", " +
                            std::to_string(e.values[i].value) + "}";
                }
                body += "}));\n";
            }
            for (const auto &k : c.classes) {
                body += node_expanded_class(k);
            }
            for (const auto &f : c.functions) {
                bool ok = (f.ret.kind == "void" || nx_marshalable(f.ret));
                for (const auto &p : f.params) {
                    ok = ok && nx_marshalable(p.type);
                }
                if (ok) {
                    body += "    exports.Set(\"" + f.name +
                            "\", Napi::Function::New(env, &rosetta::napi_free_entry<&" + f.qualified +
                            ">, \"" + f.name + "\"));\n";
                }
            }

            std::string out = "// Generated by rosetta::generate (expanded, reflection-free) — "
                              "do not edit by hand.\n";
            out += "#include <napi.h>\n";
            out += "#include <rosetta/backends/node_runtime.h>\n";
            auto add = [&](const std::string &h) { append_include(out, h); };
            for (const auto &k : c.classes) {
                add(k.header);
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            out += using_namespaces_of(c); // `using namespace` for namespaced user types
            out += node_trampolines_of(c); // reflection-free; empty when no virtuals
            out += "\nNapi::Object Init(Napi::Env env, Napi::Object exports) {\n";
            out += body;
            out += "    return exports;\n}\n\n";
            out += "NODE_API_MODULE(" + c.lib + ", Init)\n";
            return out;
        }

        inline std::string NodeExpandedBackend::render(const GenContext &c) const {
            return node_expanded_source(c);
        }

        inline void NodeExpandedBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "node-expanded";
            write_file(dir / "auto_napi.cpp", node_expanded_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(NODEX_CMAKE, c));
            write_file(dir / "package.json", render_meta(NODE_PACKAGE, c));
            write_file(dir / "README.md", readme("node-expanded", c));
        }

    } // namespace gen_detail
} // namespace rosetta
