// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Node (N-API) generation backend. Included by inline/generate.hxx, which
// provides the shared render helpers this file relies on.

#pragma once

namespace rosetta {
    namespace gen_detail {

        constexpr std::string_view NODE_CPP =
            R"CPP(// Generated by rosetta::generate — do not edit by hand.
{{INCLUDES}}#include <rosetta/visitors/node_visitor.h>
{{TRAMPOLINES}}
Napi::Object Init(Napi::Env env, Napi::Object exports) {
{{BINDINGS}}    return exports;
}

NODE_API_MODULE({{LIB}}, Init)
)CPP";

        constexpr std::string_view NODE_CMAKE = R"CMK({{HEADER_BLOCK}}
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

if(NOT NODE_ADDON_API_DIR)
    execute_process(
        COMMAND node -p "require('node-addon-api').include"
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE NODE_ADDON_API_DIR
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    string(REGEX REPLACE "^\"|\"$" "" NODE_ADDON_API_DIR "${NODE_ADDON_API_DIR}")
endif()

add_library({{LIB}} SHARED auto_napi.cpp ${CMAKE_JS_SRC})
set_target_properties({{LIB}} PROPERTIES PREFIX "" SUFFIX ".node")

target_include_directories({{LIB}} PRIVATE
    ${CMAKE_JS_INC}
    ${NODE_ADDON_API_DIR}
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

# Optional external user library (manifest "user_lib"): the bound headers only
# declare the API; its bodies live in a separately-compiled shared/static lib,
# so link against it here. Empty ⇒ this block is skipped (header-only project).
set(ROSETTA_USER_LIB "{{USER_LIB_NAME}}")
set(ROSETTA_USER_LIB_DIR "{{USER_LIB_DIR}}")
if(ROSETTA_USER_LIB)
    target_link_directories({{LIB}} PRIVATE ${ROSETTA_USER_LIB_DIR})
    # `-l` flag (not a bare name) so CMake links the external library by file
    # name and never mistakes it for a same-named project target.
    target_link_libraries({{LIB}} PRIVATE "-l${ROSETTA_USER_LIB}")
    set_target_properties({{LIB}} PROPERTIES
        BUILD_RPATH "${ROSETTA_USER_LIB_DIR}"
        INSTALL_RPATH "${ROSETTA_USER_LIB_DIR}")
endif()

target_link_libraries({{LIB}} PRIVATE ${CMAKE_JS_LIB})

target_compile_definitions({{LIB}} PRIVATE NAPI_VERSION=8)

target_compile_options({{LIB}} PRIVATE
    -freflection -freflection-latest -fexperimental-library -fannotation-attributes)

target_link_options({{LIB}} PRIVATE
    -nostdlib++ -L${ROSETTA_STDLIB} -Wl,-rpath,${ROSETTA_STDLIB}
    -lc++ -lc++abi)

if(APPLE)
    target_link_options({{LIB}} PRIVATE -Wl,-undefined,dynamic_lookup)
endif()

add_custom_command(TARGET {{LIB}} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy
        $<TARGET_FILE:{{LIB}}>
        ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
)CMK";

        constexpr std::string_view NODE_PACKAGE = R"JSON({
  "name": "{{LIB}}",
  "version": "1.0.0",
  "private": true,
  "description": "Auto-generated N-API bindings for {{LIB}}.",
  "main": "index.js",
  "scripts": {
    "build": "cmake-js compile",
    "rebuild": "cmake-js rebuild"
  },
  "devDependencies": {
    "cmake-js": "^7.3.0",
    "node-addon-api": "^8.0.0"
  }
}
)JSON";

        // Instance virtual methods of a class — the ones a trampoline must shim.
        inline std::vector<const GenMethod *> node_virtual_methods(const GenClass &k) {
            std::vector<const GenMethod *> out;
            for (const auto &m : k.methods) {
                if (m.is_virtual && !m.is_static) {
                    out.push_back(&m);
                }
            }
            return out;
        }

        // One N-API trampoline: `class Js_T : public T, public rosetta::NapiTrampoline`.
        // Each virtual override reproduces the base signature exactly and routes
        // through napi_call_override[_pure], which dispatches to the JS subclass's
        // override (or falls back to the C++ base / throws for a pure virtual).
        inline std::string node_trampoline_for(const GenClass &k) {
            const auto virts = node_virtual_methods(k);
            if (virts.empty()) {
                return {};
            }
            std::string s =
                "class Js_" + k.name + " : public " + k.name + ", public rosetta::NapiTrampoline {\npublic:\n";
            s += "    using " + k.name + "::" + k.name + ";\n";
            for (const GenMethod *m : virts) {
                const bool  is_void = (m->ret_cpp == "void");
                std::string sig     = "    " + m->ret_cpp + " " + m->name + "(";
                std::string names;  // p0, p1, ... — base-call + JS-forward args
                for (std::size_t i = 0; i < m->param_cpp.size(); ++i) {
                    const std::string pn = "p" + std::to_string(i);
                    sig += (i ? ", " : "") + m->param_cpp[i] + " " + pn;
                    names += (i ? ", " : "") + pn;
                }
                sig += ")";
                if (m->is_const) {
                    sig += " const";
                }
                if (m->is_noexcept) {
                    sig += " noexcept";
                }
                sig += " override {\n        ";

                const std::string ret   = is_void ? "" : "return ";
                const std::string targs = names.empty() ? "" : ", " + names;
                if (m->is_pure) {
                    s += sig + ret + "rosetta::napi_call_override_pure<" + k.name + ", " +
                         m->ret_cpp + ">(*this, \"" + m->name + "\"" + targs + ");\n    }\n";
                } else {
                    const std::string thunk = "[&]{ " + (is_void ? std::string() : std::string("return ")) +
                                              "this->" + k.name + "::" + m->name + "(" + names + "); }";
                    s += sig + ret + "rosetta::napi_call_override<" + k.name + ", " + m->ret_cpp +
                         ">(*this, \"" + m->name + "\", " + thunk + targs + ");\n    }\n";
                }
            }
            s += "};\n";
            return s;
        }

        inline std::string node_trampolines_of(const GenContext &c) {
            std::string body;
            for (const auto &k : c.classes) {
                body += node_trampoline_for(k);
            }
            if (body.empty()) {
                return {};
            }
            return "\nnamespace rosetta_node {\n" + body + "} // namespace rosetta_node\n";
        }

        inline std::string node_bindings(const GenContext &c) {
            std::string binds;
            for (const auto &e : c.enums) {
                binds += "    exports.Set(\"" + e.name + "\", rosetta::bind_napi_enum<" + e.name +
                         ">(env));\n";
            }
            for (const auto &k : c.classes) {
                if (node_virtual_methods(k).empty()) {
                    binds += "    exports.Set(\"" + k.name + "\", rosetta::bind_napi<" + k.name +
                             ">(env, \"" + k.name + "\"));\n";
                } else {
                    binds += "    exports.Set(\"" + k.name + "\", rosetta::bind_napi<" + k.name +
                             ", rosetta_node::Js_" + k.name + ">(env, \"" + k.name + "\"));\n";
                }
            }
            for (const auto &f : c.functions) {
                binds += "    exports.Set(\"" + f.name + "\", rosetta::bind_napi_function<^^" +
                         f.qualified + ">(env, \"" + f.name + "\"));\n";
            }
            return binds;
        }

        inline std::string node_source(const GenContext &c) {
            return subst(NODE_CPP, {{"LIB", c.lib},
                                    // includes_of() also emits the `using namespace`
                                    // a namespaced user library needs (so unqualified
                                    // trampolines / bind_napi<T> resolve).
                                    {"INCLUDES", includes_of(c)},
                                    {"TRAMPOLINES", node_trampolines_of(c)},
                                    {"BINDINGS", node_bindings(c)}});
        }

        inline std::string NodeBackend::render(const GenContext &c) const {
            return node_source(c);
        }

        inline void NodeBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "node";
            write_file(dir / "auto_napi.cpp", node_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(NODE_CMAKE, c));
            write_file(dir / "package.json", render_meta(NODE_PACKAGE, c));
            write_file(dir / "README.md", readme("node", c));
        }

    } // namespace gen_detail
} // namespace rosetta
