// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Expanded (reflection-free) QML backend, Route A. Included by
// inline/generate.hxx after qt_expanded_backend.h (reuses qtx_qstr / qtx_display
// / qtx_scalar / qtx_arg / qtx_method_ok / qtx_hint helpers) and the shared
// render helpers.

#pragma once

namespace rosetta {
    namespace gen_detail {

        constexpr std::string_view QMLX_CMAKE =
            R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# Plain QtQuick: NO C++26, NO reflection. rosetta's include dir provides the
# generic Q_OBJECT bridge (qml_reflected_object.h) and the inspector markup
# (qml/Inspector.qml); moc only ever runs on those, never on per-type reflection.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_qml CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(QT_DIR "{{QT_DIR}}" CACHE PATH "Qt 6 install prefix")
list(PREPEND CMAKE_PREFIX_PATH "${QT_DIR}")
find_package(Qt6 6.5 REQUIRED COMPONENTS Core Gui Qml Quick QuickControls2)
qt_standard_project_setup(REQUIRES 6.5)

set(ROSETTA_INCLUDE "{{ROSETTA_INCLUDE}}")
set(ROSETTA_QML "${ROSETTA_INCLUDE}/rosetta/visitors")

# The Q_OBJECT bridge lives in the include tree, so list it for AUTOMOC.
qt_add_executable({{LIB}}_qml
    main.cpp
    qml_bindings.cpp
    ${ROSETTA_QML}/qml_reflected_object.h)

set_source_files_properties(${ROSETTA_QML}/qml/Inspector.qml
    PROPERTIES QT_RESOURCE_ALIAS Inspector.qml)

qt_add_qml_module({{LIB}}_qml
    URI ReflectedQml
    VERSION 1.0
    QML_FILES ${ROSETTA_QML}/qml/Inspector.qml)

target_include_directories({{LIB}}_qml PRIVATE
    {{USER_INCLUDE}}
    ${ROSETTA_INCLUDE})

target_link_libraries({{LIB}}_qml PRIVATE
    Qt6::Core Qt6::Gui Qt6::Qml Qt6::Quick Qt6::QuickControls2)
)CMK";

        // Coarse type tag the Inspector.qml uses to pick an editor.
        inline std::string qmlx_tag(const GenType &t) {
            if (t.kind == "string")
                return "string";
            if (t.kind == "boolean")
                return "bool";
            if (t.kind == "number")
                return t.integer ? "int" : "double";
            return "other";
        }

        // QVariant expression for a field's current value (used for the info row
        // and the getter body), reading through `self`.
        inline std::string qmlx_value_expr(const GenField &f) {
            const std::string m = "self->" + f.name;
            if (f.type.kind == "string") {
                return "QVariant(QString::fromStdString(" + m + "))";
            }
            return "QVariant::fromValue(" + m + ")";
        }

        // QVariant -> field assignment expression (the converted RHS), by kind.
        inline std::string qmlx_conv(const GenType &t, const std::string &v) {
            if (t.kind == "string")
                return v + ".toString().toStdString()";
            if (t.kind == "boolean")
                return "(" + v + ".toBool())";
            if (t.kind == "number")
                return t.integer ? v + ".toInt()" : v + ".toDouble()";
            return v;
        }

        inline std::string qmlx_widget_expr(const std::vector<std::any> &anns) {
            std::string w;
            if (find_annotation<rosetta::widget::slider_tag>(anns))
                w = "slider";
            else if (find_annotation<rosetta::widget::checkbox_tag>(anns))
                w = "checkbox";
            else if (find_annotation<rosetta::widget::textfield_tag>(anns))
                w = "textfield";
            else if (find_annotation<rosetta::widget::spin_tag>(anns))
                w = "spin";
            return w.empty() ? "QString{}" : qtx_qstr(w);
        }

        inline std::string qmlx_field(const GenField &f) {
            if (!qtx_scalar(f.type)) {
                return {}; // object / vector / enum: skip (QVariant can't marshal it)
            }
            const std::string nm   = "QStringLiteral(\"" + f.name + "\")";
            const std::string disp = qtx_qstr(qtx_display(f.name, f.annotations));
            std::string       s    = "    {\n        QVariantMap info;\n";
            s += "        info[QStringLiteral(\"name\")] = " + nm + ";\n";
            s += "        info[QStringLiteral(\"displayName\")] = " + disp + ";\n";
            s += "        info[QStringLiteral(\"type\")] = " + qtx_qstr(qmlx_tag(f.type)) + ";\n";
            s += "        info[QStringLiteral(\"doc\")] = " + qtx_qstr(f.doc) + ";\n";
            s += std::string("        info[QStringLiteral(\"readonly\")] = ") +
                 (f.is_readonly ? "true" : "false") + ";\n";
            s += std::string("        info[QStringLiteral(\"hasRange\")] = ") +
                 (f.range.has ? "true" : "false") + ";\n";
            s += "        info[QStringLiteral(\"min\")] = " + num_str(f.range.min) + ";\n";
            s += "        info[QStringLiteral(\"max\")] = " + num_str(f.range.max) + ";\n";
            s += "        info[QStringLiteral(\"widget\")] = " + qmlx_widget_expr(f.annotations) +
                 ";\n";
            const bool has_cb = !f.choices.empty();
            s += std::string("        info[QStringLiteral(\"hasChoices\")] = ") +
                 (has_cb ? "true" : "false") + ";\n";
            std::string choices = "QVariantList{";
            for (std::size_t i = 0; i < f.choices.size(); ++i) {
                choices += (i ? ", " : "") + qtx_qstr(f.choices[i]);
            }
            choices += "}";
            s += "        info[QStringLiteral(\"choices\")] = " + choices + ";\n";
            s += "        info[QStringLiteral(\"value\")] = " + qmlx_value_expr(f) + ";\n";
            s += "        obj->appendField(info);\n";
            s += "        obj->registerGetter(" + nm + ", [self]() -> QVariant { return " +
                 qmlx_value_expr(f) + "; });\n";

            // setter, mirroring qml_visitor's readonly / combobox / range / plain
            s += "        obj->registerSetter(" + nm + ", ";
            if (f.is_readonly) {
                s += "[](const QVariant &) -> QString { return " + nm +
                     " + QStringLiteral(\" is read-only\"); });\n";
            } else if (has_cb) {
                s += "[self](const QVariant &v) -> QString {\n";
                s += "            const QString s = v.toString();\n";
                s += "            if (";
                for (std::size_t i = 0; i < f.choices.size(); ++i) {
                    s += (i ? " && " : "") + std::string("s != ") + qtx_qstr(f.choices[i]);
                }
                s += ")\n                return " + nm +
                     " + QStringLiteral(\" not in allowed choices\");\n";
                s += "            self->" + f.name + " = " + qmlx_conv(f.type, "v") + ";\n";
                s += "            return {};\n        });\n";
            } else if (f.range.has && f.type.kind == "number") {
                s += "[self](const QVariant &v) -> QString {\n";
                s += "            auto val = " + qmlx_conv(f.type, "v") + ";\n";
                s += "            double d = static_cast<double>(val);\n";
                s += "            if (d < " + num_str(f.range.min) + " || d > " +
                     num_str(f.range.max) + ")\n";
                s += "                return " + nm + " + QStringLiteral(\" out of range [" +
                     num_str(f.range.min) + ", " + num_str(f.range.max) + "]\");\n";
                s += "            self->" + f.name + " = val;\n";
                s += "            return {};\n        });\n";
            } else {
                s += "[self](const QVariant &v) -> QString { self->" + f.name + " = " +
                     qmlx_conv(f.type, "v") + "; return {}; });\n";
            }
            s += "    }\n";
            return s;
        }

        inline std::string qmlx_method(const std::string &cls, const GenMethod &m) {
            if (!qtx_method_ok(m)) {
                return {};
            }
            const std::string nm   = "QStringLiteral(\"" + m.name + "\")";
            const std::string disp = qtx_qstr(qtx_display(m.name, m.annotations));
            std::string       btn;
            if (const auto *b = find_annotation<rosetta::button>(m.annotations); b && b->label) {
                btn = b->label;
            }
            std::string s = "    {\n        QVariantMap info;\n";
            s += "        info[QStringLiteral(\"name\")] = " + nm + ";\n";
            s += "        info[QStringLiteral(\"displayName\")] = " + disp + ";\n";
            s += "        info[QStringLiteral(\"doc\")] = " + qtx_qstr(m.doc) + ";\n";
            s += "        info[QStringLiteral(\"button\")] = " + qtx_qstr(btn) + ";\n";
            s += "        info[QStringLiteral(\"arity\")] = " + std::to_string(m.params.size()) +
                 ";\n";
            s += std::string("        info[QStringLiteral(\"isStatic\")] = ") +
                 (m.is_static ? "true" : "false") + ";\n";
            std::string ptypes = "QVariantList{";
            for (std::size_t i = 0; i < m.params.size(); ++i) {
                ptypes += (i ? ", " : "") + qtx_qstr(qmlx_tag(m.params[i].type));
            }
            ptypes += "}";
            s += "        info[QStringLiteral(\"paramTypes\")] = " + ptypes + ";\n";
            s += "        obj->appendMethod(info);\n";

            std::string call = (m.is_static ? cls + "::" : "self->") + m.name + "(";
            for (std::size_t i = 0; i < m.params.size(); ++i) {
                call += (i ? ", " : "") + qmlx_conv(m.params[i].type,
                                                    "args.value(" + std::to_string(i) + ")");
            }
            call += ")";
            std::string body;
            if (m.ret.kind == "void") {
                body = call + "; return {};";
            } else if (m.ret.kind == "string") {
                body = "return QVariant(QString::fromStdString(" + call + "));";
            } else {
                body = "return QVariant::fromValue(" + call + ");";
            }
            const std::string cap = m.is_static ? "[]" : "[self]";
            s += "        obj->registerInvoker(" + nm + ", " + cap +
                 "(const QVariantList &args) -> QVariant { " + body + " });\n";
            s += "    }\n";
            return s;
        }

        inline std::string qmlx_bind_fn(const GenClass &k) {
            std::string s = "void rosetta_qml::bind_" + k.name + "(rosetta::ReflectedObject *obj, " +
                            k.name + " &t) {\n";
            s += "    " + k.name + " *self = &t;\n    (void)self;\n";
            for (const auto &f : k.fields) {
                s += qmlx_field(f);
            }
            for (const auto &m : k.methods) {
                s += qmlx_method(k.name, m);
            }
            s += "}\n\n";
            return s;
        }

        // First default-constructible class with a scalar field — the demo's
        // single inspector subject; falls back to the first class.
        inline const GenClass *qmlx_demo_class(const GenContext &c) {
            for (const auto &k : c.classes) {
                if (!k.is_default_constructible) {
                    continue;
                }
                for (const auto &f : k.fields) {
                    if (qtx_scalar(f.type)) {
                        return &k;
                    }
                }
            }
            for (const auto &k : c.classes) {
                if (k.is_default_constructible) {
                    return &k;
                }
            }
            return c.classes.empty() ? nullptr : &c.classes.front();
        }

        inline void QmlExpandedBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "qml-expanded";

            // header
            std::string h = "// Generated by rosetta::generate (expanded, reflection-free) — "
                            "do not edit by hand.\n#pragma once\n\n";
            h += "#include <rosetta/visitors/qml_reflected_object.h>\n";
            {
                std::string seen;
                for (const auto &k : c.classes) {
                    const std::string line = "#include \"" + k.header + "\"\n";
                    if (!k.header.empty() && seen.find(line) == std::string::npos) {
                        seen += line;
                    }
                }
                h += seen;
            }
            h += using_namespaces_of(c); // `using namespace` for namespaced user types
            h += "\nnamespace rosetta_qml {\n";
            for (const auto &k : c.classes) {
                h += "    void bind_" + k.name + "(rosetta::ReflectedObject *obj, " + k.name +
                     " &target);\n";
            }
            h += "} // namespace rosetta_qml\n";

            // source
            std::string s = "// Generated by rosetta::generate (expanded, reflection-free) — "
                            "do not edit by hand.\n#include \"qml_bindings.h\"\n\n";
            for (const auto &k : c.classes) {
                s += qmlx_bind_fn(k);
            }

            // demo main
            const GenClass   *demo = qmlx_demo_class(c);
            const std::string dn   = demo ? demo->name : std::string("Reflected");
            std::string       m    = "// Generated by rosetta::generate (expanded, reflection-free) "
                                     "— do not edit by hand.\n";
            m += "#include \"qml_bindings.h\"\n#include <QGuiApplication>\n";
            m += "#include <QQmlApplicationEngine>\n#include <QQmlContext>\n\n";
            m += "int main(int argc, char **argv) {\n    QGuiApplication app(argc, argv);\n";
            m += "    static " + dn + " obj;\n";
            m += "    rosetta::ReflectedObject reflected;\n";
            m += "    reflected.setTypeName(QStringLiteral(\"" + dn + "\"));\n";
            m += "    rosetta_qml::bind_" + dn + "(&reflected, obj);\n";
            m += "    reflected.emitReady();\n\n";
            m += "    QQmlApplicationEngine engine;\n";
            m += "    engine.rootContext()->setContextProperty(QStringLiteral(\"inspector\"), "
                 "&reflected);\n";
            m += "    engine.loadFromModule(\"ReflectedQml\", \"Inspector\");\n";
            m += "    if (engine.rootObjects().isEmpty()) return -1;\n";
            m += "    return app.exec();\n}\n";

            write_file(dir / "qml_bindings.h", h);
            write_file(dir / "qml_bindings.cpp", s);
            write_file(dir / "main.cpp", m);
            write_file(dir / "CMakeLists.txt", render_meta(QMLX_CMAKE, c));
            write_file(dir / "README.md", readme("qml-expanded", c));
        }

    } // namespace gen_detail
} // namespace rosetta
