// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Expanded (reflection-free) Qt Widgets backend. Included by inline/generate.hxx
// after python_expanded_backend.h (reuses py_lit) and the shared render helpers
// (find_annotation / write_file).

#pragma once

namespace rosetta {
    namespace gen_detail {

        constexpr std::string_view QTX_CMAKE =
            R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# Plain Qt Widgets: NO C++26, NO reflection. rosetta's include dir is on the path
# only for the header-only, reflection-free qt_widgets_runtime.h.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_qt CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)

set(QT_DIR "{{QT_DIR}}" CACHE PATH "Qt 6 install prefix")
list(PREPEND CMAKE_PREFIX_PATH "${QT_DIR}")
find_package(Qt6 6.5 REQUIRED COMPONENTS Core Gui Widgets)
qt_standard_project_setup(REQUIRES 6.5)

qt_add_executable({{LIB}}_qt main.cpp qt_inspector.cpp)

target_include_directories({{LIB}}_qt PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

target_link_libraries({{LIB}}_qt PRIVATE Qt6::Widgets)
)CMK";

        // Scalars Qt can edit inline; everything else gets the disabled
        // placeholder (matching the reflective visitor's fallback).
        inline bool qtx_scalar(const GenType &t) {
            return t.kind == "number" || t.kind == "boolean" || t.kind == "string";
        }

        // Widget hint expression from the member's annotations.
        inline std::string qtx_hint(const std::vector<std::any> &anns) {
            if (find_annotation<rosetta::widget::slider_tag>(anns))
                return "rosetta::qtw::H_SLIDER";
            if (find_annotation<rosetta::widget::checkbox_tag>(anns))
                return "rosetta::qtw::H_CHECKBOX";
            if (find_annotation<rosetta::widget::textfield_tag>(anns))
                return "rosetta::qtw::H_TEXTFIELD";
            if (find_annotation<rosetta::widget::spin_tag>(anns))
                return "rosetta::qtw::H_SPIN";
            return "rosetta::qtw::H_NONE";
        }

        // Display label: rosetta::label override, else the member name.
        inline std::string qtx_display(const std::string &name,
                                       const std::vector<std::any> &anns) {
            if (const auto *l = find_annotation<rosetta::label>(anns); l && l->text && l->text[0]) {
                return l->text;
            }
            return name;
        }

        inline std::string qtx_qstr(const std::string &s) {
            return "QStringLiteral(\"" + py_lit(s) + "\")";
        }

        // One field → an add_field<F>(...) (F deduced from t.<name>) or, for
        // non-scalar types, an add_unsupported(...).
        inline std::string qtx_field(const GenField &f) {
            const std::string disp = qtx_qstr(qtx_display(f.name, f.annotations));
            const std::string tip  = qtx_qstr(f.doc);
            if (!qtx_scalar(f.type)) {
                return "    rosetta::qtw::add_unsupported(form, " + disp + ", " + tip + ");\n";
            }
            const std::string mp = "t." + f.name;
            // combobox choices (string fields only, but harmless to always pass)
            std::string choices = "QStringList{";
            for (std::size_t i = 0; i < f.choices.size(); ++i) {
                choices += (i ? ", " : "") + qtx_qstr(f.choices[i]);
            }
            choices += "}";
            std::string s = "    rosetta::qtw::add_field(form, " + disp + ", " + tip + ", " + mp +
                            ", " + (f.is_readonly ? "true" : "false") + ", " +
                            (f.range.has ? "true" : "false") + ", " + num_str(f.range.min) + ", " +
                            num_str(f.range.max) + ", " + choices + ", " + qtx_hint(f.annotations) +
                            ",\n        [&t](auto v) { t." + f.name + " = v; }, log, \"" + f.name +
                            "\");\n";
            return s;
        }

        // Per-parameter QString → typed conversion, by IR kind.
        inline std::string qtx_arg(const GenType &t, std::size_t i) {
            const std::string a = "args.value(" + std::to_string(i) + ")";
            if (t.kind == "string") {
                return a + ".toStdString()";
            }
            if (t.kind == "boolean") {
                return "(" + a + ".toInt() != 0)";
            }
            if (t.kind == "number") {
                return t.integer ? a + ".toLongLong()" : a + ".toDouble()";
            }
            return a; // unreachable: callers skip non-marshalable methods
        }

        inline bool qtx_method_ok(const GenMethod &m) {
            const bool ret_ok =
                m.ret.kind == "void" || m.ret.kind == "number" || m.ret.kind == "boolean" ||
                m.ret.kind == "string";
            if (!ret_ok) {
                return false;
            }
            for (const auto &p : m.params) {
                if (!(p.type.kind == "number" || p.type.kind == "boolean" ||
                      p.type.kind == "string")) {
                    return false;
                }
            }
            return true;
        }

        // One method → an add_method(...) with a typed invoke lambda, or "" if
        // its signature can't cross the QVariant boundary (skipped).
        inline std::string qtx_method(const std::string &cls, const GenMethod &m) {
            if (!qtx_method_ok(m)) {
                return {};
            }
            const std::string disp = qtx_qstr(qtx_display(m.name, m.annotations));
            const std::string tip  = qtx_qstr(m.doc);
            std::string       btn;
            if (const auto *b = find_annotation<rosetta::button>(m.annotations); b && b->label) {
                btn = b->label;
            }
            std::string names = "QStringList{";
            for (std::size_t i = 0; i < m.params.size(); ++i) {
                names += (i ? ", " : "") + qtx_qstr(m.params[i].name);
            }
            names += "}";

            // call expression
            std::string call = (m.is_static ? cls + "::" : "t.") + m.name + "(";
            for (std::size_t i = 0; i < m.params.size(); ++i) {
                call += (i ? ", " : "") + qtx_arg(m.params[i].type, i);
            }
            call += ")";

            std::string body;
            if (m.ret.kind == "void") {
                body = call + "; return QStringLiteral(\"ok\");";
            } else if (m.ret.kind == "string") {
                body = "return QString::fromStdString(" + call + ");";
            } else if (m.ret.kind == "boolean") {
                body = "return (" + call +
                       ") ? QStringLiteral(\"true\") : QStringLiteral(\"false\");";
            } else { // number
                body = "return QString::number(" + call + ");";
            }

            const std::string cap     = m.is_static ? "[]" : "[&t]";
            const std::string argname = m.params.empty() ? "const QStringList&"
                                                          : "const QStringList& args";
            std::string       lambda =
                cap + "(" + argname + ") -> QString { " + body + " }";

            return "    rosetta::qtw::add_method(form, " + disp + ", " + tip + ", " + qtx_qstr(btn) +
                   ", " + names + ",\n        " + lambda + ", log, \"" + m.name + "\");\n";
        }

        inline std::string qtx_build_fn(const GenClass &k) {
            std::string s = "QWidget *rosetta_qt::build_" + k.name + "_inspector(" + k.name +
                            " &t, bool with_log) {\n";
            s += "    auto shell = rosetta::qtw::make_shell(QStringLiteral(\"" + k.name +
                 "\"), with_log);\n";
            s += "    QFormLayout *form = shell.form;\n";
            s += "    QTextEdit *log = shell.log;\n";
            s += "    (void)log;\n";
            for (const auto &f : k.fields) {
                s += qtx_field(f);
            }
            for (const auto &m : k.methods) {
                s += qtx_method(k.name, m);
            }
            s += "    return shell.root;\n}\n\n";
            return s;
        }

        inline std::string qtx_header(const GenContext &c) {
            std::string s = "// Generated by rosetta::generate (expanded, reflection-free) — "
                            "do not edit by hand.\n#pragma once\n\n";
            auto        add = [&](const std::string &h) {
                if (!h.empty()) {
                    const std::string line = "#include \"" + h + "\"\n";
                    if (s.find(line) == std::string::npos) {
                        s += line;
                    }
                }
            };
            for (const auto &k : c.classes) {
                add(k.header);
            }
            s += using_namespaces_of(c); // `using namespace` for namespaced user types
            s += "\nclass QWidget;\n\nnamespace rosetta_qt {\n";
            for (const auto &k : c.classes) {
                s += "    QWidget *build_" + k.name + "_inspector(" + k.name +
                     " &target, bool with_log = false);\n";
            }
            s += "} // namespace rosetta_qt\n";
            return s;
        }

        inline std::string qtx_source(const GenContext &c) {
            std::string s = "// Generated by rosetta::generate (expanded, reflection-free) — "
                            "do not edit by hand.\n";
            s += "#include \"qt_inspector.h\"\n";
            s += "#include <rosetta/visitors/qt_widgets_runtime.h>\n\n";
            for (const auto &k : c.classes) {
                s += qtx_build_fn(k);
            }
            return s;
        }

        inline std::string qtx_main(const GenContext &c) {
            std::string s = "// Generated by rosetta::generate (expanded, reflection-free) — "
                            "do not edit by hand.\n";
            s += "// Demo: one inspector tab per default-constructible class.\n";
            s += "#include \"qt_inspector.h\"\n#include <QApplication>\n#include <QTabWidget>\n\n";
            s += "int main(int argc, char **argv) {\n";
            s += "    QApplication app(argc, argv);\n";
            s += "    auto *tabs = new QTabWidget();\n";
            for (const auto &k : c.classes) {
                if (!k.is_default_constructible) {
                    continue;
                }
                s += "    static " + k.name + " " + k.name + "_obj;\n";
                s += "    tabs->addTab(rosetta_qt::build_" + k.name + "_inspector(" + k.name +
                     "_obj, true), QStringLiteral(\"" + k.name + "\"));\n";
            }
            s += "    tabs->resize(460, 540);\n    tabs->show();\n    return app.exec();\n}\n";
            return s;
        }

        inline void QtExpandedBackend::emit(const GenContext &c) const {
            auto dir = c.out_dir / "qt-expanded";
            write_file(dir / "qt_inspector.h", qtx_header(c));
            write_file(dir / "qt_inspector.cpp", qtx_source(c));
            write_file(dir / "main.cpp", qtx_main(c));
            write_file(dir / "CMakeLists.txt", render_meta(QTX_CMAKE, c));
            write_file(dir / "README.md", readme("qt-expanded", c));
        }

    } // namespace gen_detail
} // namespace rosetta
