// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// WebAssembly (emscripten/embind) generation backend — registered under the
// "wasm" target. Included by inline/generate.hxx, which provides the shared
// render helpers this file relies on.

#pragma once

namespace rosetta {
    namespace gen_detail {

        constexpr std::string_view WASM_CPP =
            R"CPP(// Generated by rosetta::generate — do not edit by hand.
{{INCLUDES}}#include <rosetta/visitors/wasm_visitor.h>

EMSCRIPTEN_BINDINGS({{LIB}}) {
{{BINDINGS}}}
)CPP";

        constexpr std::string_view WASM_CMAKE =
            R"CMK(# Generated by rosetta::generate — do not edit by hand.
cmake_minimum_required(VERSION 3.28)
project({{LIB}}_binding CXX)

if(NOT EMSCRIPTEN)
    message(FATAL_ERROR "Configure via `emcmake cmake ...` (emsdk required).")
endif()

set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

add_executable({{LIB}} auto_emscripten.cpp{{USER_SOURCES}})

target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})

# Optional external user library (manifest "user_lib"). WebAssembly cannot link a
# native .dylib/.so and has no rpath, so the manifest's `link` choice is overridden
# here: the library is ALWAYS the wasm static archive (lib{{USER_LIB_NAME}}.a)
# compiled with the SAME emsdk. Referenced by full path so a same-named project
# target is never linked by mistake. Empty name ⇒ skipped.
set(ROSETTA_USER_LIB "{{USER_LIB_NAME}}")
set(ROSETTA_USER_LIB_DIR "{{USER_LIB_DIR}}")
if(ROSETTA_USER_LIB)
    target_link_directories({{LIB}} PRIVATE ${ROSETTA_USER_LIB_DIR})
    set(_rosetta_static "${ROSETTA_USER_LIB_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}${ROSETTA_USER_LIB}${CMAKE_STATIC_LIBRARY_SUFFIX}")
    if(EXISTS "${_rosetta_static}")
        target_link_libraries({{LIB}} PRIVATE "${_rosetta_static}")
    else()
        target_link_libraries({{LIB}} PRIVATE "-l${ROSETTA_USER_LIB}")
    endif()
endif()

target_compile_options({{LIB}} PRIVATE
    {{REFLECTION_FLAGS}})

target_link_options({{LIB}} PRIVATE
    --bind -sMODULARIZE=1 -sEXPORT_NAME=createModule
    -sENVIRONMENT=node,web -sALLOW_MEMORY_GROWTH=1 -sDISABLE_EXCEPTION_CATCHING=0)

set_target_properties({{LIB}} PROPERTIES SUFFIX ".js")
)CMK";

        inline void WasmBackend::emit(const GenContext &c) const {
            std::string binds;
            // Enums first so class fields/methods can resolve them.
            for (const auto &e : c.enums) {
                binds += "    rosetta::bind_wasm_enum<" + e.name + ">(\"" + e.name + "\");\n";
            }
            for (const auto &k : c.classes) {
                binds += "    rosetta::bind_wasm<" + k.name + ">(\"" + k.name + "\");\n";
            }
            for (const auto &f : c.functions) {
                binds += "    emscripten::function(\"" + f.name + "\", &" + f.qualified +
                         ");\n";
            }
            auto dir = c.out_dir / "wasm";
            write_file(dir / "auto_emscripten.cpp", render_source(WASM_CPP, c, binds));
            write_file(dir / "CMakeLists.txt", render_meta(WASM_CMAKE, c));
            write_file(dir / "README.md", readme("wasm", c));
        }

    } // namespace gen_detail
} // namespace rosetta
