#pragma once
#include "CodeWriter.h"

// ============================================================================
// Python setup.py Generator
// ============================================================================
class PythonSetupPyGenerator : public CodeWriter {
  public:
    using CodeWriter::CodeWriter;

    void generate() override {
        line("#!/usr/bin/env python3");
        line("\"\"\"");
        line("Setup script for " + config_.module_name);
        line("Generated by binding_generator");
        line("\"\"\"");
        line();
        line("import os");
        line("import sys");
        line("from setuptools import setup, Extension");
        line("from setuptools.command.build_ext import build_ext");
        line();
        line("class get_pybind_include:");
        line("    def __str__(self):");
        line("        import pybind11");
        line("        return pybind11.get_include()");
        line();
        line("ext_modules = [");
        line("    Extension(");
        line("        '" + config_.module_name + "',");
        line("        sources=['generated_pybind11.cxx'],");
        line("        include_dirs=[");
        line("            get_pybind_include(),");
        line("            '.',");
        line("            '..',");
        for (const auto &inc : config_.include_dirs) {
            std::string cleaned = inc;
            // Remove CMake variables for setup.py
            if (cleaned.find("${") != std::string::npos)
                continue;
            line("            '" + cleaned + "',");
        }
        line("        ],");
        line("        language='c++',");
        line("        extra_compile_args=['-std=c++20', "
             "'-fvisibility=hidden'],");
        line("    ),");
        line("]");
        line();
        line("setup(");
        line("    name='" + config_.module_name + "',");
        line("    version='" + config_.version + "',");
        line("    author='" + config_.author + "',");
        line("    description='" + config_.description + "',");
        line("    ext_modules=ext_modules,");
        line("    install_requires=['pybind11>=2.10', 'numpy'],");
        line("    python_requires='>=3.8',");
        line("    cmdclass={'build_ext': build_ext},");
        line(")");
    }
};
