#pragma once
#include "../CodeWriter.h"

// ============================================================================
// REST API README Generator
// ============================================================================

class RestApiReadmeGenerator : public CodeWriter {
public:
    using CodeWriter::CodeWriter;

    void generate() override {
        line("# " + config_.module_name + " - REST API Server");
        line();
        line("REST API server generated from Rosetta introspection.");
        line();
        line("## Build");
        line();
        line("```bash");
        line("mkdir build && cd build");
        line("cmake ..");
        line("make");
        line("```");
        line();
        line("## Run");
        line();
        line("```bash");
        line("./" + config_.module_name + "_server --port 8080");
        line("```");
        line();
        line("Options:");
        line("- `--host HOST` - Bind address (default: 0.0.0.0)");
        line("- `--port PORT` - Listen port (default: 8080)");
        line();
        line("## API Endpoints");
        line();
        line("### Health Check");
        line();
        line("```");
        line("GET /health");
        line("```");
        line();
        line("Response:");
        line("```json");
        line("{\"status\": \"ok\", \"module\": \"" + config_.module_name + "\"}");
        line("```");
        line();
        line("### List Classes");
        line();
        line("```");
        line("GET /api/classes");
        line("```");
        line();
        line("Response:");
        line("```json");
        line("{");
        line("  \"error\": false,");
        line("  \"data\": [\"Model\", \"Surface\", \"Solver\"]");
        line("}");
        line("```");
        line();
        line("### Get Class Info");
        line();
        line("```");
        line("GET /api/classes/:name");
        line("```");
        line();
        line("Response:");
        line("```json");
        line("{");
        line("  \"error\": false,");
        line("  \"data\": {");
        line("    \"name\": \"Model\",");
        line("    \"cpp_type\": \"mylib::Model\",");
        line("    \"constructors\": [");
        line("      {\"params\": []},");
        line("      {\"params\": [\"std::string\"]}");
        line("    ],");
        line("    \"methods\": [");
        line("      {\"name\": \"compute\", \"return_type\": \"void\", \"params\": [], \"is_const\": false},");
        line("      {\"name\": \"get_result\", \"return_type\": \"double\", \"params\": [], \"is_const\": true}");
        line("    ]");
        line("  }");
        line("}");
        line("```");
        line();
        line("### List Objects");
        line();
        line("```");
        line("GET /api/objects");
        line("```");
        line();
        line("Response:");
        line("```json");
        line("{");
        line("  \"error\": false,");
        line("  \"data\": [");
        line("    {\"id\": \"Model_1\", \"class\": \"Model\"},");
        line("    {\"id\": \"Surface_2\", \"class\": \"Surface\"}");
        line("  ]");
        line("}");
        line("```");
        line();
        line("### Create Object");
        line();
        line("```");
        line("POST /api/objects/:class");
        line("Content-Type: application/json");
        line();
        line("[arg1, arg2, ...]  // Constructor arguments");
        line("```");
        line();
        line("Example:");
        line("```bash");
        line("curl -X POST http://localhost:8080/api/objects/Model \\");
        line("  -H \"Content-Type: application/json\" \\");
        line("  -d '[\"config.json\"]'");
        line("```");
        line();
        line("Response:");
        line("```json");
        line("{");
        line("  \"error\": false,");
        line("  \"data\": {\"id\": \"Model_1\", \"class\": \"Model\"}");
        line("}");
        line("```");
        line();
        line("### Call Method");
        line();
        line("```");
        line("POST /api/objects/:id/:method");
        line("Content-Type: application/json");
        line();
        line("[arg1, arg2, ...]  // Method arguments");
        line("```");
        line();
        line("Example:");
        line("```bash");
        line("# Call method with no arguments");
        line("curl -X POST http://localhost:8080/api/objects/Model_1/compute");
        line();
        line("# Call method with arguments");
        line("curl -X POST http://localhost:8080/api/objects/Model_1/set_position \\");
        line("  -H \"Content-Type: application/json\" \\");
        line("  -d '[[1.0, 2.0, 3.0]]'");
        line("```");
        line();
        line("Response:");
        line("```json");
        line("{");
        line("  \"error\": false,");
        line("  \"data\": 42.5  // Return value (if any)");
        line("}");
        line("```");
        line();
        line("### Delete Object");
        line();
        line("```");
        line("DELETE /api/objects/:id");
        line("```");
        line();
        line("Example:");
        line("```bash");
        line("curl -X DELETE http://localhost:8080/api/objects/Model_1");
        line("```");
        line();
        line("## Error Responses");
        line();
        line("All errors follow this format:");
        line();
        line("```json");
        line("{");
        line("  \"error\": true,");
        line("  \"message\": \"Error description\",");
        line("  \"code\": 400");
        line("}");
        line("```");
        line();
        line("Common error codes:");
        line("- `400` - Bad request (invalid parameters)");
        line("- `404` - Not found (class or object doesn't exist)");
        line("- `500` - Internal server error");
        line();
        line("## CORS");
        line();
        line("CORS is enabled by default, allowing requests from any origin.");
        line();
        line("## Example Client (JavaScript)");
        line();
        line("```javascript");
        line("const API_BASE = 'http://localhost:8080/api';");
        line();
        line("// Create an object");
        line("async function createModel(configPath) {");
        line("  const res = await fetch(`${API_BASE}/objects/Model`, {");
        line("    method: 'POST',");
        line("    headers: {'Content-Type': 'application/json'},");
        line("    body: JSON.stringify([configPath])");
        line("  });");
        line("  const data = await res.json();");
        line("  return data.data.id;");
        line("}");
        line();
        line("// Call a method");
        line("async function compute(objectId) {");
        line("  const res = await fetch(`${API_BASE}/objects/${objectId}/compute`, {");
        line("    method: 'POST'");
        line("  });");
        line("  return await res.json();");
        line("}");
        line();
        line("// Delete an object");
        line("async function deleteObject(objectId) {");
        line("  await fetch(`${API_BASE}/objects/${objectId}`, {method: 'DELETE'});");
        line("}");
        line();
        line("// Usage");
        line("const modelId = await createModel('config.json');");
        line("const result = await compute(modelId);");
        line("console.log(result);");
        line("await deleteObject(modelId);");
        line("```");
        line();
        line("## Example Client (Python)");
        line();
        line("```python");
        line("import requests");
        line();
        line("API_BASE = 'http://localhost:8080/api'");
        line();
        line("# Create an object");
        line("res = requests.post(f'{API_BASE}/objects/Model', json=['config.json'])");
        line("model_id = res.json()['data']['id']");
        line();
        line("# Call a method");
        line("res = requests.post(f'{API_BASE}/objects/{model_id}/compute')");
        line("print(res.json())");
        line();
        line("# Delete");
        line("requests.delete(f'{API_BASE}/objects/{model_id}')");
        line("```");
    }
};
