// ============================================================================
// Binding Generator for geometry
// ============================================================================
// Generated by rosetta-create
//
// This generator compiles the project and calls the Rosetta registration
// function BEFORE generating bindings, so the generator can discover all
// registered classes.
// ============================================================================

#include <rosetta/extensions/generators/common/BindingGeneratorLib.h>
#include "geometry_registration.h"

int main(int argc, char* argv[]) {
    // IMPORTANT: Call registration BEFORE running the generator
    // This populates rosetta::Registry::instance() with class metadata
    geometry_rosetta::register_all();

    // Now run the binding generator
    // It will query the registry and find all registered classes
    return BindingGeneratorLib::run(argc, argv);
}
