// SPDX-FileCopyrightText: Copyright (c) fmaerten@gmail.com
// SPDX-License-Identifier: UNLICENSED

// Framework-level rosetta_gen tool. Reads manifest.json and emits a
// per-project tool source tree:
//
//   <out_dir>/bindings.h        rosetta::binding_info<T> specializations
//   <out_dir>/<lib>_gen.cpp     main() with one generate<T> per class
//   <out_dir>/CMakeLists.txt    builds <lib>_gen
//
// `<lib>` is the first class's `lib` field — the binding library /
// module name. The user then compiles `<lib>_gen` and runs it to emit
// the per-backend bindings.

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <nlohmann/json.hpp>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;
using json   = nlohmann::json;

struct ClassEntry {
    std::string              name;
    std::string              header;
    std::string              lib;
    std::vector<std::string> targets;
};

struct Manifest {
    fs::path                user_include;     // absolute
    fs::path                rosetta_include;  // absolute
    std::vector<ClassEntry> classes;

    // CMake target / binary basename — first class's lib + "_gen".
    std::string target() const {
        if (classes.empty())
            throw std::runtime_error("manifest has no class entries");
        return classes.front().lib + "_gen";
    }
};

static Manifest load(const fs::path &manifest_path) {
    std::ifstream in(manifest_path);
    if (!in)
        throw std::runtime_error("cannot open " + manifest_path.string());
    json j;
    in >> j;

    Manifest       m;
    const fs::path base = fs::absolute(manifest_path).parent_path();

    m.user_include = fs::weakly_canonical(
        base / fs::path(j.at("user_include").get<std::string>()));
    m.rosetta_include = fs::weakly_canonical(
        base / fs::path(j.at("rosetta_include").get<std::string>()));

    for (const auto &c : j.at("classes")) {
        ClassEntry e;
        e.name   = c.at("name").get<std::string>();
        e.header = c.at("header").get<std::string>();
        e.lib    = c.at("lib").get<std::string>();
        for (const auto &t : c.at("targets"))
            e.targets.push_back(t.get<std::string>());
        m.classes.push_back(std::move(e));
    }

    if (m.classes.empty())
        throw std::runtime_error("manifest has no class entries");

    return m;
}

static void write_file(const fs::path &p, const std::string &content) {
    fs::create_directories(p.parent_path());
    std::ofstream(p) << content;
}

static std::string render_bindings_h(const Manifest &m) {
    std::ostringstream out;
    out << "// Generated by rosetta_gen — do not edit by hand.\n"
        << "#pragma once\n\n"
        << "#include <array>\n"
        << "#include <rosetta/generate.h>\n";
    for (const auto &c : m.classes)
        out << "#include \"" << c.header << "\"\n";
    out << "\n";
    for (const auto &c : m.classes) {
        out << "template <> struct rosetta::binding_info<" << c.name << "> {\n"
            << "    static constexpr std::array  targets{";
        bool first = true;
        for (const auto &t : c.targets) {
            if (!first)
                out << ", ";
            first = false;
            out << "\"" << t << "\"";
        }
        out << "};\n"
            << "    static constexpr const char *lib    = \"" << c.lib << "\";\n"
            << "    static constexpr const char *header = \"" << c.header << "\";\n"
            << "};\n\n";
    }
    return out.str();
}

static std::string render_project_gen_cpp(const Manifest &m) {
    const std::string target = m.target();
    std::ostringstream out;
    out << "// Generated by rosetta_gen — do not edit by hand.\n"
        << "#include \"bindings.h\"\n"
        << "#include <cstdio>\n"
        << "#include <cstring>\n\n"
        << "namespace {\n"
        << "    const char *arg(int argc, char **argv, const char *flag) {\n"
        << "        for (int i = 1; i + 1 < argc; ++i)\n"
        << "            if (std::strcmp(argv[i], flag) == 0) return argv[i + 1];\n"
        << "        return nullptr;\n"
        << "    }\n"
        << "}\n\n"
        << "int main(int argc, char **argv) {\n"
        << "    rosetta::GenerateOptions opt;\n"
        << "    if (const char *v = arg(argc, argv, \"--out\")) opt.out_dir = v;\n"
        << "    opt.user_include    = \"" << m.user_include.string() << "\";\n"
        << "    opt.rosetta_include = \"" << m.rosetta_include.string() << "\";\n\n"
        << "    if (opt.out_dir.empty()) {\n"
        << "        std::fprintf(stderr, \"usage: " << target << " --out <dir>\\n\");\n"
        << "        return 1;\n"
        << "    }\n\n";
    for (const auto &c : m.classes)
        out << "    rosetta::generate<" << c.name << ">(opt);\n";
    out << "\n    std::fprintf(stderr, \"wrote scaffolding to %s\\n\",\n"
        << "                 opt.out_dir.string().c_str());\n"
        << "    return 0;\n"
        << "}\n";
    return out.str();
}

static std::string render_cmakelists(const Manifest &m) {
    const std::string target = m.target();
    std::ostringstream out;
    out << "# Generated by rosetta_gen — do not edit by hand.\n"
        << "cmake_minimum_required(VERSION 3.28)\n\n"
        << "set(CLANG_P2996_ROOT \"$ENV{HOME}/devs/c++/clang-p2996/build\"\n"
        << "    CACHE PATH \"Bloomberg clang-p2996 fork build directory\")\n"
        << "if(NOT CMAKE_CXX_COMPILER)\n"
        << "    set(CMAKE_C_COMPILER   \"${CLANG_P2996_ROOT}/bin/clang\")\n"
        << "    set(CMAKE_CXX_COMPILER \"${CLANG_P2996_ROOT}/bin/clang++\")\n"
        << "endif()\n\n"
        << "project(" << target << " CXX)\n\n"
        << "set(CMAKE_CXX_STANDARD 26)\n"
        << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n"
        << "set(CMAKE_CXX_EXTENSIONS OFF)\n"
        << "set(CMAKE_CXX_SCAN_FOR_MODULES OFF)\n\n"
        << "add_executable(" << target << " " << target << ".cpp)\n\n"
        << "target_include_directories(" << target << " PRIVATE\n"
        << "    " << m.user_include.string() << "\n"
        << "    " << m.rosetta_include.string() << ")\n\n"
        << "target_compile_options(" << target << " PRIVATE\n"
        << "    -freflection -freflection-latest -fexperimental-library -fannotation-attributes)\n\n"
        << "target_link_options(" << target << " PRIVATE\n"
        << "    -nostdlib++ -L${CLANG_P2996_ROOT}/lib -Wl,-rpath,${CLANG_P2996_ROOT}/lib\n"
        << "    -lc++ -lc++abi)\n";
    return out.str();
}

int main(int argc, char **argv) {
    if (argc < 2 || argc > 3) {
        std::fprintf(stderr, "usage: rosetta_gen <manifest.json> [out_dir]\n");
        return 1;
    }
    const fs::path manifest_path = argv[1];
    const fs::path out_dir       = (argc == 3)
            ? fs::path(argv[2])
            : fs::absolute(manifest_path).parent_path() / "generated";

    try {
        const Manifest    m      = load(manifest_path);
        const std::string target = m.target();
        write_file(out_dir / "bindings.h", render_bindings_h(m));
        write_file(out_dir / (target + ".cpp"), render_project_gen_cpp(m));
        write_file(out_dir / "CMakeLists.txt", render_cmakelists(m));

        std::fprintf(stderr,
                     "wrote %s/{bindings.h, %s.cpp, CMakeLists.txt}\n",
                     out_dir.string().c_str(),
                     target.c_str());
    } catch (const std::exception &e) {
        std::fprintf(stderr, "rosetta_gen: %s\n", e.what());
        return 1;
    }

    return 0;
}
