#pragma once
#include "../common/CodeWriter.h"

// ============================================================================
// Python setup.py Generator - Modernized
// Generates setup.py with all source files and platform-specific compiler flags
// ============================================================================
class PythonSetupPyGenerator : public CodeWriter {
public:
    using CodeWriter::CodeWriter;

    void generate() override {
        emit(R"(
#!/usr/bin/env python3
"""
Setup script for ${MODULE}
Generated by binding_generator
"""

import os
import sys
import platform
from setuptools import setup, Extension
from setuptools.command.build_ext import build_ext

class get_pybind_include:
    def __str__(self):
        import pybind11
        return pybind11.get_include()

# Source files
SOURCES = [
    'generated_pybind11.cxx',
)", {{"MODULE", config_.module_name}});

        // Add library source files if in static mode
        if (config_.should_compile_sources()) {
            for (const auto &src : config_.source_files) {
                line("    '" + src + "',");
            }
        }

        emit(R"(
]

# Include directories
INCLUDE_DIRS = [
    get_pybind_include(),
    '.',
)");

        // Add include directories
        for (const auto &inc : config_.include_dirs) {
            if (inc.find("${") != std::string::npos) continue;  // Skip CMake variables
            line("    '" + inc + "',");
        }

        emit(R"(
]

# Library directories
LIBRARY_DIRS = [
)");

        // Add library directories
        for (const auto &lib_dir : config_.library_dirs) {
            if (lib_dir.find("${") != std::string::npos) continue;  // Skip CMake variables
            line("    '" + lib_dir + "',");
        }

        emit(R"(
]

# Libraries to link
LIBRARIES = [
)");

        // Add libraries
        for (const auto &lib : config_.link_libraries) {
            line("    '" + lib + "',");
        }

        emit(R"(
]

# Platform-specific compiler and linker flags
if platform.system() == 'Windows':
    extra_compile_args = ['/std:c++20', '/EHsc', '/O2']
    extra_link_args = []
else:
    extra_compile_args = ['-std=c++20', '-fvisibility=hidden', '-O3']
    extra_link_args = []
    if platform.system() == 'Darwin':
        extra_compile_args += ['-stdlib=libc++', '-mmacosx-version-min=10.15']
        extra_link_args += ['-stdlib=libc++', '-mmacosx-version-min=10.15']

ext_modules = [
    Extension(
        '${MODULE}',
        sources=SOURCES,
        include_dirs=INCLUDE_DIRS,
        library_dirs=LIBRARY_DIRS,
        libraries=LIBRARIES,
        language='c++',
        extra_compile_args=extra_compile_args,
        extra_link_args=extra_link_args,
    ),
]

setup(
    ext_modules=ext_modules,
    cmdclass={'build_ext': build_ext},
)
)", {{"MODULE", config_.module_name}});
    }
};
