// Generated by rosetta::generate — do not edit by hand.
#include <rosetta/annotations.h>
#include "shapes.h"
#include <rosetta/visitors/python_visitor.h>

namespace rosetta_py {
class Py_Shape : public Shape {
public:
    using Shape::Shape;
    double area() const override {
        PYBIND11_OVERRIDE_PURE(double, Shape, area, );
    }
    std::string describe() const override {
        PYBIND11_OVERRIDE(std::string, Shape, describe, );
    }
};
} // namespace rosetta_py

PYBIND11_MODULE(shapes, m) {
    m.doc() = "Auto-generated bindings for shapes.";
    rosetta::bind_pybind<Shape, rosetta_py::Py_Shape>(m, "Shape");
}
