"""Demonstrates pybind11 trampolines generated by rosetta.

`Shape` is an abstract C++ class (pure virtual `area`, virtual `describe`).
Because the generated bindings use a Py_Shape trampoline, Python subclasses can
override those virtuals and C++ dispatches back into Python.

Run after building:  python3 test_shapes.py
"""

import math
import shapes


class Circle(shapes.Shape):
    def __init__(self, r):
        super().__init__()           # constructs the trampoline
        self.label = "circle"        # inherited C++ field
        self.r = r

    def area(self):                  # overrides the pure virtual
        return math.pi * self.r * self.r

    def describe(self):              # overrides the virtual-with-default
        return f"{self.label} r={self.r}"


class Square(shapes.Shape):
    def __init__(self, s):
        super().__init__()
        self.s = s

    def area(self):                  # overrides the pure virtual
        return self.s * self.s
    # describe() NOT overridden -> falls back to the C++ default body


c = Circle(2.0)
assert math.isclose(c.area(), math.pi * 4.0), c.area()
assert c.describe() == "circle r=2.0", c.describe()

s = Square(3.0)
assert math.isclose(s.area(), 9.0), s.area()
# describe() not overridden in Square -> C++ Shape::describe() returns label:
assert s.describe() == "shape", s.describe()

# Calling the pure virtual with no Python override must raise (OVERRIDE_PURE):
try:
    shapes.Shape().area()
    raise SystemExit("FAIL: un-overridden pure virtual should raise")
except RuntimeError:
    pass

print("trampoline OK: Python overrides dispatched through C++ virtuals")
